rsb.connectionEditor = rsb.connectionEditor || function(props) {var DEFAULTS = {getDriverInfo: function(providerName, connectionStringType, callback) { throw rsb.evalTemplate('The $func$ function is not implemented.', {"func": "getDriverInfo"}); },parseConnectionString: function(providerName, connectionString, callback){ throw rsb.evalTemplate('The $func$ function is not implemented.', {"func": "parseConnectionString"}); },buildConnectionString: function(providerName, sensitiveType, callback){ throw rsb.evalTemplate('The $func$ function is not implemented.', {"func": "buildConnectionString"}); },setHierarchyPorp: function(name, value){ throw rsb.evalTemplate('The $func$ function is not implemented.', {"func": "setHierarchyPorp"}); },getHierarchyPorp: function(name){ throw rsb.evalTemplate('The $func$ function is not implemented.', {"func": "getHierarchyPorp"}); }};var _props = $.extend(DEFAULTS, props);var _providerNameSelect = $("#connProviderNameSelect");var _providerNameOther = $("#connProviderNameOther");var _propListContainer = $("#connPropertyListContainer");var _connStrContainer = $("#connConnectionStringContainer");var _otherContainer = $("#connOtherContainer");var _fmtContainer = $("#connFormatContainer");var _connStr = $("#connConnectionString");var _encryptedConnStr = $("#encryptedConnStr");var _fmtProperty = $("#connFormatPropertyList");var _fmtConnStr = $("#connFormatConnectionString");var _providerName = null;var _curConnStr = null;var _curEncryptedConnStr = null;var _connProps = null;var _curCapabilities = null;var _setConnectionString = function(val) {_curConnStr = val;_connStr.val(_curConnStr)};var _getConnectionString = function() {return _connStr.val()}
var _setEncryptedConnString = function(val) {_curEncryptedConnStr = val;_encryptedConnStr.val(_curEncryptedConnStr)};var _getEncryptedConnString = function() {return _encryptedConnStr.val()}
var _setProviderName = function(provierName) {if (_providerName != provierName) {_providerName = provierName;_providerNameSelect.val(provierName)}};var _getProviderName = function() {return _providerName || _providerNameSelect.val()};var _isKnownProviderName = function(providerName) {var isKnown = false;_providerNameSelect.find("option.known").each(function(){if (!isKnown) {isKnown = $(this).val() == providerName}});return isKnown};var _getPropertyValue = function(name) {const value = _props.getHierarchyPorp(name.toLowerCase());if (value) {return value}
if (_connProps) {return _connProps.find(prop => prop.name.toLowerCase() === name.toLowerCase())?.default}
return null}
var _changeConnStrFormat = function(connectionString, callback) {_connProps = null;_fmtConnStr.prop("checked", true);_fmtProperty.prop("checked", false);_connStrContainer.removeClass('hidden');_propListContainer.addClass('hidden');if (connectionString != null) {_setConnectionString(connectionString);if (callback) callback()} else {_props.buildConnectionString(_getProviderName(), "Encrypt", function(connStr) {_setConnectionString(connStr);if (callback) callback(connStr)})}};var _changePropertyFormat = function(props, connectionString, callback) {_curConnStr = null;_fmtProperty.prop("checked", true);_fmtConnStr.prop("checked", false);_connStrContainer.addClass('hidden');_propListContainer.removeClass('hidden');if (null != props) {_connProps = props;if (_propListContainer.find("input,select").length <= 0) {_changeProvider(_getProviderName(), function(result) {if (callback) callback(result)})} else {for (var name in props) {var input = _propListContainer.find("[name='" + rsb.escapeSelector(name) + "']");if (input && input.length && (!input.val() || input.attr("type") != "password")) {input.val(props[name]);props[name] && input.trigger("updateCentralSetting")}}
rsb.connect.initVaultInputGroups(rsb.connect.conn.connectionForm, rsb.connect.conn.connectionErrorContainer);if (callback) callback()}}};var _changeFormat = function(isPropertyList, connectionString, callback) {if (isPropertyList) {connectionString = connectionString || _connStr.val();_props.parseConnectionString(_getProviderName(), connectionString, function(props, success) {if (success) {_changePropertyFormat(props, connectionString, callback)} else {_changeConnStrFormat(connectionString, callback)}})} else {_changeConnStrFormat(connectionString, callback)}};var _changeProvider = function(providerName, callback) {if (providerName) {_setProviderName(providerName)} else {providerName = _getProviderName()}
_curCapabilities = "";_setConnectionString("");_propListContainer.empty();if (_isKnownProviderName(providerName)) {_providerNameSelect.attr("name", "ProviderName");_providerNameOther.removeAttr("name");_fmtContainer.removeClass("hidden");_otherContainer.addClass("hidden");_props.getDriverInfo(providerName, function(result) {var html = "";var advancedProp = [];var oauthInputs = "";rsb.forEach(result, function(prop, index) {if (prop.choice && typeof prop.choice === "string" && prop.choice.length > 1) {prop.choice = [prop.choice]}
if (!prop.category && prop.tab) {prop.category = prop.tab}
prop.issensitive = (prop.sensitivity?.toUpperCase() == "SENSITIVE" || prop.sensitivity?.toUpperCase() == "PASSWORD" || false);if (prop.hasOwnProperty("capabilities")) {_curCapabilities = (prop.capabilities || "").toUpperCase()} else if (prop.issessionproperty?.toLowerCase() == "true") {var pv = _getPropertyValue(prop.name) || (prop.value || prop.default || "");oauthInputs += "<input type='text' class='hidden rsb-form-nosubmit' name='" + prop.name.toLowerCase() +  "' value='" + pv +  "'>"} else if (prop.category?.toLowerCase() == "basic" || prop.isrequired?.toLowerCase() == "true" || prop.ishierarchy?.toLowerCase() == "true") {html += _getPropertyHtml(prop)} else if (prop.category?.toLowerCase() != "oauth") {advancedProp.push(prop)}});var btn = '<button type="button" class="btn btn-outline-secondary" id="testConnectionButton" onclick="rsb.connect.conn.testConnection($(this));" data-loading-text="' + 'Connecting...'+ '"><i class="fa fa-exchange"></i> ' + 'Test Connection'+ '</button>';if ((_curCapabilities || "").indexOf("OAUTH") >= 0) {oauthInputs = '<div id="oauthContainer">' + oauthInputs + "</div>";var validateOAuth = false;const accessTokenProp = _connProps ? _connProps.find(prop => prop.name.toLowerCase() === name.toLowerCase()) : null;if (accessTokenProp?.default?.length > 0) {validateOAuth = true}
btn = '<button type="button" id="apiConnectBtn" onclick="rsb.connect.conn.resetConnection();" class="btn btn-outline-secondary ' + (validateOAuth ? "hidden" : "") + '" data-loading-text="' + 'Connecting...'+ '"><i class="fa fa-exchange"></i> ' + 'Connect To'+ " " + providerName  + '</button>' + '<button type="button" id="apiDisconnectBtn" class="btn btn-outline-secondary ' + (validateOAuth ? "" : "hidden") + '" data-loading-text="' +  'Disconnecting ...'+ '"onclick="rsb.connect.conn.disconnect();return false;"><i class="fa fa-close"></i> Disconnect from '  + providerName + '</button>'}
html += oauthInputs + '<div class="form-group row mb-3 testconnection"><div class="col-md-3"></div><div class="col-md-9">' + btn + '</div></div>';advancedProp.sort(function(a, b) {if (a.category && b.category) {return a.category.localeCompare(b.category)} else if (b.category) {return -1} else if (a.category) {return 1} else {return 0}});if (advancedProp.length > 0) {const otherProp = {isrequired: "False",description: "",issessionproperty: "False",type: "String",default: "",tab: "advanced",ishierarchy: "False",displayname: "Other Driver Settings",name: "other",style: "text",placeholder: "",sensitivity: "",category: "Optional Connection Properties"};advancedProp.push(otherProp);html += '<h4 id="toggleAdvanced" class="pointercursor page-header" style="margin-bottom:0px">' +'  <i id="toggleAdvancedIcon" class="fa fa-chevron-right"></i>' + 'Advanced'+'</h4>' +'<div id="advancedSettings" class="panel-collapse collapse" role="tabpanel" style="margin-top: 1em;">';var lastCategory = "";rsb.forEach(advancedProp, function(prop, index) {if (prop.category && prop.category != lastCategory) {html += '<h4 class="page-header">' + prop.category + '</h4>'
lastCategory = prop.category}
html += _getPropertyHtml(prop)});html += '</div>'}
_propListContainer.append(html);rsb.connect.initVaultInputGroups(rsb.connect.conn.connectionForm, rsb.connect.conn.connectionErrorContainer);$('#toggleAdvanced').click(function() {$('#advancedSettings').collapse('toggle')});$('#advancedSettings').on('hidden.bs.collapse', function () {$("#toggleAdvancedIcon").removeClass('fa-chevron-down').addClass('fa-chevron-right')});$('#advancedSettings').on('show.bs.collapse', function () {$("#toggleAdvancedIcon").removeClass('fa-chevron-right').addClass('fa-chevron-down')});_propListContainer.find('[data-bs-toggle="popover"]').popover({container: _propListContainer});_initHierarchy();if (callback) callback(result)});rsb.connect.conn.connEditor.ensureConnectionString()} else {_setProviderName("Other");_providerNameOther.val(providerName == "Other" ? "" : providerName);_providerNameSelect.removeAttr("name");_providerNameOther.attr("name", "ProviderName");_fmtContainer.addClass("hidden");_otherContainer.removeClass("hidden");_changeFormat(false, "");if (callback) callback()}}
var _getPropertyHtml = function(prop) {var html = "";var isOther = prop.displayname.toLowerCase() == "other";prop.value = _getPropertyValue(prop.name) || (prop.value || prop.default || "");html += '<div class="form-group row mb-3 ';if (prop.ishierarchy.toLowerCase() == 'true') {html += " hierarchy-controller"}
html += '">' +'<label for="' + prop.name.toLowerCase() + '" class="col-md-3 control-label col-form-label">' + (isOther ? 'Other (Optional)' : prop.displayname) + ':</label>';if (!prop.issensitive && prop.choice && prop.choice.length > 1) {html += '<div class="col-md-5">' +'<select class="form-control form-select rsb-form-nosubmit" name="' + prop.name.toLowerCase() + '"' + (prop.description && prop.description.length > 0 ? 'data-bs-placement="top" data-bs-toggle="popover" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + prop.description + '"' : '') + '>';rsb.forEach(prop.choice, function(choice, index) {html += '<option class="rsb-form-nosubmit" value="' + choice + '"' + (choice == prop.value ? ' selected' : '') + '>' + (choice || 'Not Specified') + '</option>'});html += '</select>'} else {if (prop.type == undefined) {prop.type = "text"}
var widthClass = (prop.type == "file" || isOther ? "col-md-6" : prop.type == "int" ? "col-md-4" : "col-md-6");var inputType = (prop.issensitive ? 'password' : 'text');html += '<div class="' + widthClass + '">' +'<input type="' + inputType + '" class="form-control rsb-form-nosubmit" name="' + prop.name.toLowerCase() + '" value="' + prop.value + '"' + (prop.description && prop.description.length > 0 ? 'data-bs-toggle="popover" data-bs-html="true" data-bs-trigger="hover" data-bs-placement="top" data-bs-content="' + prop.description + '"' : '') + (prop.issensitive ? 'autocomplete="new-password"' : '') + '>'}
html += '</div></div>';return html}
var _initHierarchy = function () {_propListContainer.find(".form-group.hierarchy-controller").each(function () {var $controller = $(this).find("input,select");if (!$controller || !$controller.length) {return true}
var $name = $controller.attr("name");if (!$name) {return true}
if ($controller.is("input")) {if ($controller.attr("type") == "checkbox" || $controller.attr("type") == "radio") {$controller.off("change").on("change", function () {_controllerChanged($name, $(this).prop("checked"))})} else {$controller.off("keyup").off("change").on("keyup change", function () {_controllerChanged($name, $(this).val())})}} else if ($controller.is("select")) {$controller.off("change").on("change", function () {_controllerChanged($name, $(this).val())})}})}
var _controllerChanged = function (name, value) {_props.setHierarchyPorp(name, value);_changeProvider(null)}
_providerNameSelect.on("change", function() {_curConnStr = _connProps = null;_changeProvider(_providerNameSelect.val())});_fmtProperty.on("click", function() { _changeFormat(true); });_fmtConnStr.on("click", function() { _changeFormat(false); });this.init = function(providerName, connectionString, callback) {_curConnStr = _providerName = _connProps = null;_setProviderName(providerName);_propListContainer.empty();_otherContainer.addClass("hidden");_changeFormat(_isKnownProviderName(providerName) && _fmtProperty.prop("checked"), connectionString, callback)};this.ensureConnectionString = function() {var resultContainer = $("#testConnectionResult");var connectionString = _getConnectionString();if (_fmtProperty.prop("checked")) {_props.buildConnectionString(_getProviderName(), "Encrypt", function(connStr) {connectionString = connStr})}
var maskData = rsb.connect.conn.getBasicPostData(_getProviderName());maskData["connectionString"] = connectionString;$.ajax({dataType: "json",async: false,url: 'src/apiGetEncryptedConnectionString.rsb',type: "POST",data: maskData,success: function(data) {var errorMsg = rsb.getResultErrorMessage(data.items);if (errorMsg) {rsb.showResult(resultContainer, 'Connection error'+ ':' + errorMsg, false)} else {_setConnectionString(data.items[0].connectionstring);_setEncryptedConnString(data.items[0].connectionstring)}}})};this.buildOAuthConnectionString = function() {_props.buildConnectionString(_getProviderName(), "Encrypt", function(connStr) {_setConnectionString(connStr);_setEncryptedConnString(connStr)})}
this.getCapabilities = function() {return _curCapabilities}}
rsb.connect.conn = rsb.connect.conn || {};rsb.connect.conn.options = {};rsb.connect.conn.connectionForm = $("#apiSettingsForm");rsb.connect.conn.connectionErrorContainer = rsb.getFormResultContainer(rsb.connect.conn.connectionForm);rsb.connect.conn.hierarchyPorps = {};rsb.connect.conn.init = function($options) {rsb.connect.conn.options = $.extend($options, rsb.connect.options)}
rsb.connect.conn.getDriverInfo = function(providerName, callback) {var postData = rsb.connect.conn.getProviderInfoPostData(providerName);$.ajax({dataType: "json",url: 'src/getProviderProperties.rsb',type: "POST",data: postData,success: function(data) {var result = data["items"];if (result && result.length) {var errorMsg = rsb.getResultErrorMessage(result);if (errorMsg) {rsb.showResult(rsb.connect.conn.connectionErrorContainer, errorMsg, false)} else {callback(result)}}}})};rsb.connect.conn.parseConnectionString = function(providerName, connectionString, callback) {var postData = rsb.connect.conn.getBasicPostData(providerName);postData.ConnectionString = connectionString;postData.SensitiveType = "Encrypt";$.ajax({dataType: "json",url: 'src/parseConnectionString.rsb',type: "POST",data: postData,success: function(data) {var success = true;var props;var result = data["items"];if (result) {var errorMsg = rsb.getResultErrorMessage(result);if (errorMsg) {success = false;rsb.showResult(rsb.connect.conn.connectionErrorContainer, errorMsg, false)} else {props = result}
if (callback) {callback(props, success)}}}})};rsb.connect.conn.buildConnectionString = function(providerName, sensitiveType, callback) {var postData = rsb.connect.conn.getConnectionSettings($("#connPropertyListContainer"));postData.SensitiveType = sensitiveType || "Raw";$.ajax({dataType: "json",async: false,url: 'src/buildConnectionString.rsb',type: "POST",async: false,data: $.extend(postData, rsb.connect.conn.getBasicPostData(providerName)),success: function(data) {var result = data["items"];if (result && result.length) {var errorMsg = rsb.getResultErrorMessage(result);if (errorMsg) {rsb.showResult(rsb.connect.conn.connectionErrorContainer, errorMsg, false)} else {callback(result[0]["connectionstring"])}}}})};rsb.connect.conn.getConnectionSettings = function(container) {var data = {};$(container).find("input, select").not(".api-form-nosubmit").each(function() {data[$(this).attr("name")] = $(this).val()});if (!data["connectionstringtype"]) {data["connectionstringtype"] = $("#connectionStringType").val()}
return data}
rsb.connect.conn.getBasicPostData = function(driverName, connectionStringType) {if (driverName == "Microsoft SQL Server") {driverName = "SQL Server"} else if (driverName == "Oracle Database") {driverName = "Oracle"}
return {"@json": true,"DriverName": driverName,"DriverType": rsb.connect.conn.options.driverType,"DriverClass": rsb.connect.conn.options.driverClass[driverName] || driverName,"ConnectionStringType": connectionStringType,"connectorid": rsb.connect.conn.options.portId,"workspaceid": rsb.connect.conn.options.workspaceid}}
rsb.connect.conn.getProviderInfoPostData = function(driverName) {if (driverName == "Microsoft SQL Server") {driverName = "SQL Server"} else if (driverName == "Oracle Database") {driverName = "Oracle"}
const hierarchies = {};Object.entries(rsb.connect.conn.hierarchyPorps).forEach(([key, value], index) => {hierarchies[`HierarchyProperty#${index + 1}`] = key;hierarchies[`HierarchyPropertyValue#${index + 1}`] = value});return {"@json": true,"ProviderName": driverName,"ProviderType": rsb.connect.conn.options.driverType,"ProviderClass": rsb.connect.conn.options.driverClass[driverName] || driverName,...hierarchies,"connectorid": rsb.connect.conn.options.portId,"workspaceid": rsb.connect.conn.options.workspaceid}}
rsb.connect.conn.connEditor = new rsb.connectionEditor({getDriverInfo: rsb.connect.conn.getDriverInfo,parseConnectionString: rsb.connect.conn.parseConnectionString,buildConnectionString: rsb.connect.conn.buildConnectionString,setHierarchyPorp: (name, value) => rsb.connect.conn.hierarchyPorps[name] = value,getHierarchyPorp: (name) => rsb.connect.conn.hierarchyPorps[name] || null});rsb.connect.conn.setSelDefVal = function () {document.getElementById("connProviderNameSelect").defaultValue = $("#connProviderNameSelect").val()}
rsb.connect.conn.testConnection = function(testBtn) {var resultContainer = $("#testConnectionResult");if (resultContainer.length < 1) {resultContainer = rsb.connect.conn.connectionErrorContainer}
rsb.connect.conn.connEditor.ensureConnectionString();testBtn.button("loading");rsb.connect.conn.ensureVaultSettings();var queryData = rsb.getFormData(rsb.connect.conn.connectionForm, true);var postData = { workspaceid: queryData["workspaceid"], connectorid: queryData["connectorid"], connectortype: queryData["connectortype"] };for (var key in queryData) {postData["param@" + key] = queryData[key]}
rsb.testConnection(postData, testBtn, resultContainer, function(){rsb.connect.conn.connectionForm.submit()})}
rsb.connect.conn.formatConnectionstring = function(connectionstring, providerName) {var match = connectionstring.match(/Password=[^;]*/ig);if (match && match.length > 0) {rsb.forEach(match, function(pwd, index) {connectionstring = connectionstring.replace(pwd, pwd.substr(0, 9) + "******")})}
else if (rsb.connect.conn.options.env == "java" && "oracle database" == providerName.toLowerCase()) {var serverIndex = connectionstring.indexOf('@');var passwdIndex = connectionstring.indexOf('/');if (passwdIndex > 0 && passwdIndex < serverIndex) {connectionstring = connectionstring.substring(0, passwdIndex + 1) + "******" + connectionstring.substring(serverIndex)}}
else if(rsb.connect.conn.options.env != "java" && "db2" == providerName.toLowerCase()) {match = connectionstring.match(/PWD=[^;]*/ig);if (match && match.length > 0) {rsb.forEach(match, function(pwd, index) {connectionstring = connectionstring.replace(pwd, pwd.substr(0, 4) + "******")})}}
return connectionstring}
rsb.connect.conn.resetConnection = function() {var form = rsb.connect.conn.connectionForm;var capabilities = rsb.connect.conn.connEditor.getCapabilities();var connBtn = $("#apiConnectBtn");var disconnBtn = $("#apiDisconnectBtn");rsb.connect.conn.connEditor.buildOAuthConnectionString();var queryData = rsb.getFormData(rsb.connect.conn.connectionForm, true);rsb.connect.resetConnection(queryData, connBtn, rsb.connect.conn.connectionErrorContainer, capabilities, function(data) {rsb.connect.conn.setOAuthToForm(data);rsb.connect.conn.connEditor.buildOAuthConnectionString();return rsb.getFormData(rsb.connect.conn.connectionForm, true)}, function(data, result, oauth_callback) {connBtn.addClass('hidden');disconnBtn.removeClass('hidden');form.submit();rsb.connect.oauthWarning(oauth_callback, rsb.connect.conn.connectionErrorContainer)})}
rsb.connect.conn.disconnect = function () {var form = rsb.connect.conn.connectionForm;var connBtn = $("#apiConnectBtn");var disconnBtn = $("#apiDisconnectBtn");disconnBtn.button("loading");rsb.connect.clearOAuthToken(rsb.connect.conn.options.workspaceid, rsb.connect.conn.options.portId, function (data) {disconnBtn.button("reset");disconnBtn.addClass('hidden');connBtn.removeClass('hidden');$("#oauthContainer input").val('');form.submit()}, function (errMsg) {disconnBtn.button("reset");rsb.showResult(rsb.connect.conn.connectionErrorContainer, "<b>" + 'Failure!'+ "</b>&nbsp;&nbsp;" + errMsg, false, true)})}
rsb.connect.conn.setOAuthToForm = function(data) {$("#oauthContainer input").each(function (){var name = $(this).attr("name");if (data.hasOwnProperty(name)) {if (data[name]) {$(this).val(data[name] || "")}}})}
rsb.connect.conn.ensureVaultSettings = function() {rsb.connect.conn.connectionForm.find(".vault-input-group input").addClass("rsb-form-nosubmit").each(function() {if ($(this).attr("name").endsWith("@")) { $(this).removeClass("rsb-form-nosubmit"); }})}
$(document).ready(function() {rsb.connect.conn.connectionForm.on("beforeSubmit", function() {rsb.connect.conn.ensureVaultSettings();rsb.connect.conn.connEditor.ensureConnectionString()});rsb.connect.conn.connEditor.init($("#connProviderNameSelect").val(), $("#connConnectionString").val(), function() {var readonly = !rsb.connectorList[rsb.connect.conn.options.workspaceid.toLowerCase()].connectors[rsb.connect.conn.options.portId.toLowerCase()].allowedPrivileges.includes("updatesettings");rsb.connect.initRestrictionFeatures((readonly ? "true" : "disabled"), $(".port-tab-content #connection"))});rsb.connect.conn.setSelDefVal()});