rsb.connectionPanel = function ($options) {const CLICK_TIMER_DELAY = 200;const DEFAULTS = {fixHeight: 0,removeAble: true,endpointConfig: {paintStyle: {radius: 5,fill: "#456"},connectorStyle: {outlineStroke: '#ffffff00',outlineWidth: 3,stroke: 'rgb(220, 220, 220)',strokeWidth: 2.2},connectorHoverStyle: {stroke: '#456',strokeWidth: 2.5},maxConnections: -1},callbacks: {highlightConnection: function ($sourceId, $targetId, $originalEvent, $hoverCallback) {console.log("Highlight the connection between " + $sourceId + " and " + $sourceId + ".")},removeConnection: function ($sourceId, $targetId, $originalEvent) {console.log("Removed the connection between " + $sourceId + " and " + $targetId + ".");return true}}};var _options = $.extend(DEFAULTS, $options);var _container = $(_options.container).addClass("connection-panel-container");if (!_container.length) {throw 'The connection panel container is required.'}
var EndpointContainer = function ($panel, $key, $options) {var _key = ($key || "default").toLowerCase();var _defaultConfig = $.extend($.extend({}, $options.endpointConfig), $options[_key + "EndpointConfig"]);var _idSequence = 0;var _scrollTop = 0;var _timers = [null, null];var _lastId = null;var _endpointContainer = $panel.find(".endpoint-container." + _key);if (!_endpointContainer.length) {_endpointContainer = $("<ul class='endpoint-container " + _key + "'></ul>");$panel.append(_endpointContainer)}
_endpointContainer.attr("id", _endpointContainer.attr("id") || _key + "_endpoint-container_" + Date.now());_endpointContainer.empty();var _isVisiable = function ($endpoint, $height) {var $top = $endpoint.position().top;if ($top + $endpoint.height() < _scrollTop) {return false}
if ($top > _scrollTop + $height) {return false}
return true}
var _search = function ($array, $low, $high, $checkFn) {if ($low >= $high) {return -1}
var $middle = ($low + $high) >>> 1;var $checkRes = $checkFn($array[$middle], $middle);if ($checkRes == 0) {return $middle}
var $result = -1;if ($checkRes & 1) {$result = _search($array, $low, $middle, $checkFn)}
if ($result != -1) {return $result}
if ($checkRes & 2) {$result = _search($array, $middle + 1, $high, $checkFn)}
return $result}
var _clearTimers = function () {_loop(_timers, function ($timer, $index) {_timers[$index] = null;!!$timer && clearTimeout($timer)})}
this.insert = function ($plumbInstance, $preId, $heigth, $title, $config) {var $id = _key + "_endpoint_" + ++_idSequence;var $endpoint = $("<li class='endpoint' id='" + $id + "' style='height: " + $heigth + "px;'></li>");!!$title && $endpoint.text($title);if (_lastId == $preId) {_endpointContainer.append($endpoint);_lastId = $id} else {$preId = !!$preId && $plumbInstance.getEndpoint($preId);if (!!$preId && !!$preId.element) {$endpoint.insertAfter($($preId.element))} else {$endpoint.prependTo(_endpointContainer)}}
$plumbInstance.addEndpoint($endpoint[0], $.extend({uuid: $id,cssClass: _key + "-anchor",enabled: false}, $config), _defaultConfig);return $id}
this.scrollTop = function ($plumbInstance, $top, $force) {$top = !!$force && $top == -1 ? _scrollTop : ($top || 0);if (!$force && _scrollTop == $top) {return false}
_clearTimers();_endpointContainer.css("top", -(_scrollTop = $top));_timers[0] = setTimeout(function () {var $height = _endpointContainer.height();var $children = _endpointContainer.children();var $range = [-1, $children.length];var $hiddenEndpoints = [];if ($options.fixHeight > 10) {$range = [Math.floor(_scrollTop / _options.fixHeight) - 1, Math.ceil((_scrollTop + $height) / $options.fixHeight) + 1]} else {var $pivot = _search($children, 0, $children.length, function ($child, $index) {return _isVisiable($($child), $height) ? 0 : 3});if (_scrollTop > 0 && !_isVisiable($($children[0]), $height)) {for (var $index = $pivot - 1; $index > -1; $index--) {if (!_isVisiable($($children[$index]), $height)) {$range[0] = $index;break} else {$range[0] = $index - 1}}}
if (!_isVisiable($($children[$children.length - 1]), $height)) {for (var $index = $pivot + 1; $index < $children.length; $index++) {if (!_isVisiable($($children[$index]), $height)) {$range[1] = $index;break} else {$range[1] = $index + 1}}}}
_endpointContainer.children().each(function ($index) {var $endpoint = $plumbInstance.getEndpoint(this.id);var $visible = $index > $range[0] && $index < $range[1];if (!!$endpoint && $visible != $endpoint.isVisible()) {$visible && $endpoint.setVisible(!$endpoint.isVisible(), false, true);!$visible && $hiddenEndpoints.push($endpoint)}});!!_timers[1] && clearTimeout(_timers[1]);_timers[1] = setTimeout(function () {var $isSuspend = !!$plumbInstance.getSuspendedAt();!$isSuspend && $plumbInstance.setSuspendDrawing(true);_loop($hiddenEndpoints, function ($endpoint) {$endpoint.setVisible(false, true, true);$endpoint.connections.length && _loop($endpoint.connections, function ($connection) {$connection.isVisible() && !$connection.endpoints.reduce(function ($visiable, $ele) { return $visiable || $ele.isVisible(); }, false) && $connection.setVisible(false)})});!$isSuspend && $plumbInstance.setSuspendDrawing(false, false)}, 50)}, 0)}
this.clear = function ($plumbInstance) {_endpointContainer.children().each(function () {$plumbInstance.deleteEndpoint(this.id)});_endpointContainer.empty();_endpointContainer.css("top", _scrollTop = 0);_clearTimers();_lastId = null}
return this}
var _plumbInstance = jsPlumbBrowserUI.newInstance({container: _container[0],connectionsDetachable: false,elementsDraggable: false});var _sourceEndpointContainer = new EndpointContainer(_container, "source", _options);var _targetEndpointContainer = new EndpointContainer(_container, "target", _options);var _connectorOptions = {};var _clickTimer = null;_plumbInstance.bind(jsPlumbBrowserUI.EVENT_CONNECTION_CLICK, function ($conn, $originalEvent) {_stopTimer();_clickTimer = setTimeout(function () {_clickTimer = null;(!$conn.getData() || !$conn.getData().removed) && _options.callbacks.highlightConnection($conn.sourceId, $conn.targetId, $originalEvent, function () { !$conn.isHover() && _plumbInstance.setHover($conn, true); })}, CLICK_TIMER_DELAY)})
!!_options.removeAble && _plumbInstance.bind(jsPlumbBrowserUI.EVENT_CONNECTION_DBL_CLICK, function ($conn, $originalEvent) {_stopTimer();if (_options.callbacks.removeConnection($conn.sourceId, $conn.targetId, $originalEvent)) {_plumbInstance.deleteConnection($conn);$conn.mergeData({removed: true})}})
var _loop = function ($array, $callbackFn) {$array = $array || [];for (var $index = 0; $index < $array.length; $index++) {if ($callbackFn($array[$index], $index) === false) {break}}}
var _stopTimer = function () {!!_clickTimer && clearInterval(_clickTimer);_clickTimer = null}
var _deleteEndpoint = function ($endpointId) {var $endpoint = !!$endpointId && _plumbInstance.getEndpoint($endpointId);!!$endpoint && $($endpoint.element).remove();!!$endpoint && _plumbInstance.deleteEndpoint($endpoint)}
var _getConnections = function ($endpointUUID, $remove) {var $endpoint = _plumbInstance.getEndpoint($endpointUUID);var $connections = !!$endpoint && !!$endpoint.connections ? $endpoint.connections.slice() : [];!!$remove && _deleteEndpoint($endpointUUID);return $connections}
var _connect = function ($sourceId, $tartgetId) {var $connections = _getConnections($sourceId);for (var $index = 0; $index < $connections.length; $index++) {if ($connections[$index].targetId == $tartgetId) {return $connections[$index]}}
var $connection = _plumbInstance.connect({source: _plumbInstance.getEndpoint($sourceId) || $sourceId,target: _plumbInstance.getEndpoint($tartgetId) || $tartgetId}, _connectorOptions);return $connection}
var _initConnectorSettings = function ($useBezierConnector) {_connectorOptions = {};if (!!$useBezierConnector) {_connectorOptions.connector = {type: 'Bezier',options: {curviness: 100}}}
if (!!_options.removeAble) {_connectorOptions.overlays = [{type: 'Label', options: {label: $('<div></div>').html("&times;").text(),location: 0.5,events: {click: function ($overlay, $originalEvent) {if (_options.callbacks.removeConnection($sourceId, $tartgetId, $originalEvent)) {_plumbInstance.deleteConnection($connection);$connection.mergeData({removed: true})}}}}}]}}
_initConnectorSettings(_options.useBezierConnector != false);this.insertSourceEndpoint = function ($preId, $height, $title) {return _sourceEndpointContainer.insert(_plumbInstance, $preId, $height || _options.fixHeight, $title, {anchors: 'Right'})}
this.insertTargetEndpoint = function ($preId, $height, $title) {return _targetEndpointContainer.insert(_plumbInstance, $preId, $height || _options.fixHeight, $title, {anchors: 'Left'})}
this.removeSourceEndpoint = function ($id, $fallbackId) {!!$fallbackId && !!$id && _loop(_getConnections($id, true), function ($connection) {_connect($fallbackId, $connection.targetId)});!!$id && _deleteEndpoint($id)}
this.removeTargetEndpoint = function ($id, $fallbackId) {!!$fallbackId && !!$id && _loop(_getConnections($id, true), function ($connection) {_connect($connection.sourceId, $fallbackId)});!!$id && _deleteEndpoint($id)}
this.hoverConnections = function ($endpointId, $hover) {var $endpoint = !!$endpointId && _plumbInstance.getEndpoint($endpointId);!!$endpoint && _plumbInstance.setHover($endpoint, $hover != false)}
this.getTargetEndpoints = function ($sourceId, $removeConnection) {var $targetIdMap = Object.create(null);$removeConnection = $removeConnection != false;_loop(_getConnections($sourceId), function ($connection) {$targetIdMap[$connection.targetId] = true;$removeConnection && _plumbInstance.deleteConnection($connection)})
return Object.keys($targetIdMap)}
this.connect = function ($sourceId, $tartgetId) {return _connect($sourceId, $tartgetId)}
this.disconnect = function ($sourceId, $tartgetId) {var $endpointUUID = $sourceId || $tartgetId;!!$endpointUUID && _loop(_getConnections($endpointUUID), function ($connection) {if (!$sourceId || !$tartgetId || $connection.targetId == $tartgetId) {_plumbInstance.deleteConnection($connection);return !$sourceId || !$tartgetId}})}
this.scrollTop = function ($cfg, $force) {$cfg = $cfg || {};if (!!$cfg.source || $cfg.source == 0) {_sourceEndpointContainer.scrollTop(_plumbInstance, $cfg.source, $force)}
if (!!$cfg.target || $cfg.target == 0) {_targetEndpointContainer.scrollTop(_plumbInstance, $cfg.target, $force)}}
this.useBezierConnector = function ($enable) {_initConnectorSettings($enable != false)}
this.getConnectionCount = function () {return _plumbInstance.getConnections().length}
this.refresh = function () {!_plumbInstance.getSuspendedAt() && _plumbInstance.repaintEverything();!!_options.callbacks.refreshDone && _options.callbacks.refreshDone()}
this.setSuspendDrawing = function ($suspend, $repaintAfterwards) {_plumbInstance.setSuspendDrawing($suspend != false, $suspend == false && $repaintAfterwards != false)}
this.isSuspendDrawing = function () {return !!_plumbInstance.getSuspendedAt()}
this.clear = function ($cfg) {$cfg = $cfg || {source: true, target: true};_stopTimer();_plumbInstance.deleteEveryConnection();if (!!$cfg.source && !!$cfg.target) {_plumbInstance.reset()}
!!$cfg.source && _sourceEndpointContainer.clear(_plumbInstance);!!$cfg.target && _targetEndpointContainer.clear(_plumbInstance)}
return this}
