var Field = function($field) {this.name = "";this.label = "";this.index = undefined;this.row = undefined;this.width = 6;this.offset = 0;this.type = "text";this.defaultValue = "";this.availableValues = [];this.required = false;this.readonly = false;this.value = "";var onMouseenter = function() {if (this.offsetWidth < this.scrollWidth) {$(this).attr("title", $(this).text())} else {var field = $(this).closest(".form-designer-item").data("instance");if (field.name != field.label) {$(this).attr("title", this.name)} else {$(this).attr("title", "")}}}
var onEdit = function() {var fieldObj = $(this).closest(".form-designer-item");var instance = fieldObj.data("instance");rsb.formPortPropertyEditor.show([{ "name": "Name", "value": instance.name, "readonly": true }, { "name": "Label", "value": instance.label }], function($data) {rsb.formPortSettingsForm.designer.setUnSaved();instance.label = $data.Label;fieldObj.find(".form-designer-item-title label").text($data.Label != undefined ? $data.Label : "")}, null, null, 'Edit Form Field')}
var onDelete = function() {rsb.connect.hidePopover(this);rsb.formPortSettingsForm.designer.setUnSaved();$(this).closest(".form-designer-item").trigger("rsb.formPort.deleteField", [$(this).closest(".form-designer-item")]);$(this).closest(".form-designer-item").remove()}
var onValueChange = function() {$(this).closest(".form-userview-item").data("instance").value = $(this).val()}
this.getUI = function() {var html = "";var obj = null;if (this.type != "section") {html = '<div class="form-designer-item" title=' + (this.name != this.label ? this.name : '') + '>' +'  <div class="form-designer-item-title"><label></label></div>';if (!rsb.formPortSettingsForm.readonly) {html += '  <div class="form-designer-item-icon form-designer-item-icon-edit">' +'    <i class="fa fa-edit" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Edit field'+ '"></i>' +'  </div>' +'  <div class="form-designer-item-icon form-designer-item-icon-delete">' +'    <i class="fa fa-trash-o" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Delete field'+ '"></i>' +'  </div>'}
html += '</div>';obj = $(html);obj.data("instance", this);obj.find(".form-designer-item-title label").text(this.label).mouseenter(onMouseenter);if (!rsb.formPortSettingsForm.readonly) {obj.find(".form-designer-item-icon-edit").click(onEdit);obj.find(".form-designer-item-icon-delete").click(onDelete);obj.find(".form-designer-item-icon-edit i").popover();obj.find(".form-designer-item-icon-delete i").popover()}
return obj}}
this.getJSON = function() {return {"name": this.name,"label": this.label,"index": this.index,"row": this.row,"width": this.width,"offset": this.offset,"type": this.type,"defaultValue": this.defaultValue,"availableValues": this.availableValues,"required": this.required,"readonly": this.readonly,}}
this.getUserView = function() {var html = "";var obj = null;if (this.type == "section") {html = '<div class="form-userview-item">' +'  <h3></h3>' +'</div>';obj = $(html);obj.find("h3").text(this.label)} else {html = '<div class="form-userview-item">' +'  <div class="form-group row mb-3">' +'    <label class="col-md-12 control-label col-form-label"></label>' +'    <div class="col-md-12">' +'      <input class="form-control form-data-input rsb-form-nosubmit">' +'    </div>' +'  </div>' +'</div>';obj = $(html);obj.find("label").text(this.label + ":");obj.find("input").attr("type", this.type).attr("value", this.value != undefined ? this.value : this.defaultValue).attr("savedvalue", this.value != undefined ? this.value : this.defaultValue).prop("required", this.required).prop("readonly", this.readonly).change(onValueChange)}
obj.data("instance", this);return obj}
this.getDataJSON = function() {var json = {};json[this.name] = this.value;return json}
this.copy = function() {var newField = new Field(this);return newField}
this.setReadOnly = function($isreadonly) {this.readonly = $isreadonly}
if ($field) {this.name = $field.name || this.name;this.label = $field.label || this.name || this.label;this.index = $field.index != undefined ? $field.index : this.index;this.row = $field.row != undefined ? $field.row : this.row;this.width = $field.width || this.width;this.offset = $field.offset || this.offset;this.type = $field.type || this.type;this.defaultValue = $field.defaultValue || this.defaultValue;this.availableValues = $field.availableValues || this.availableValues;this.required = $field.required || this.required;this.readonly = $field.readonly || this.readonly;this.value = $field.value != undefined ? $field.value : this.value}}
var Form = function($form) {this.name = ""
this.label = "";this.minOccurs = -1;this.maxOccurs = -1;this.boxes = [];this.readonly = false;this.index = undefined;var onTitleChange = function() {var form = $(this).closest(".form-designer-form").data("instance");form.label = $(this).val();form.name = rsb.formPortSettingsForm.designer.checkXML($(this).val())}
var onDeleteBox = function() {var box = $(this).closest(".form-designer-box");rsb.confirmModal({title: box.data("instance").type == "section" ? 'Remove Section': 'Remove Detail',body: box.data("instance").type == "section" ? 'This will remove the section and any form fields within it. Are you sure you want to proceed?': 'This will remove the detail and any form fields within it. Are you sure you want to proceed?',ok: function() {var parentForm = box.closest(".form-designer-form").data("instance");parentForm.removeBox(box.data("instance"));parentForm.updateIndex();box.remove();rsb.formPortSettingsForm.designer.setUnSaved()},cancelText: 'Cancel'});return false}
var onAddRowClick = function() {rsb.formPortSettingsForm.designer.setUnSaved();var boxObj = ($(this).siblings(".form-designer-box").length > 0) ? $(this).siblings(".form-designer-box") : $(this).closest(".form-designer-box");var newRow = new Row();boxObj.data("instance").addRow(newRow);var rowContainer = boxObj.find(".form-designer-row-container");rowContainer.append(newRow.getUI())}
var onDeleteRow = function($event, $rowObj) {rsb.formPortSettingsForm.designer.setUnSaved();var row = $rowObj.data("instance");var box = $rowObj.closest(".form-designer-box").data("instance");box.deleteRow(row);$rowObj.remove();return false}
this.addSubformBox = function($box) {if (!$box) {$box = new Box();$box.type = "section";$box.addRow()}
this.boxes.push($box)}
this.getSubformCount = function() {var count = 0;for (var i in this.subformRows) {if (this.subformRows[i].getSubform()) {count++}}
return count}
this.getUI = function() {var html = '<div class="form-designer-form">' +'  <div class="form-designer-form-title form-validate-error-container page-header">' +'    <input type="text" name="formtitle" placeholder="' + 'Click to add a form title...'+'"' + 'class="form-control form-designer-form-title-name rsb-form-nosubmit" required>' +'  </div>' +'  <div class="form-designer-boxes-container">' +'  </div>' +'</div>';var obj = $(html);var titleInput = obj.find(".form-designer-form-title input");titleInput.val(this.name);if (!rsb.formPortSettingsForm.readonly) {titleInput.change(onTitleChange)} else {titleInput.prop("readonly", true)}
obj.data("instance", this);var boxesContainer = obj.find(".form-designer-boxes-container");this.boxes.forEach(function($elem) {boxesContainer.append($elem.getUI())});return obj}
this.getUIAsSubForm = function() {var html = '<div class="form-designer-form">' +'  <div class="form-designer-box-title form-validate-error-container">' +'    <span class="form-designer-box-icon"><i class="fa fa-table"></i></span><input type="text" name="detail' + rsb.securityRand() + '" class="form-designer-box-title-name rsb-form-nosubmit" required>' +'  </div>';if (!rsb.formPortSettingsForm.readonly) {html +=  '  <div class="form-designer-form-icon form-designer-box-icon-delete">' +'    <i class="fa fa-times" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="left" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Remove detail'+ '"></i>' +'  </div>'}
html +=    '  <div class="form-designer-box">' +'    <div class="form-designer-row-container"></div>' +'  </div>';if (!rsb.formPortSettingsForm.readonly) {html +=  '  <div class="form-designer-form-icon form-designer-form-icon-add-row">' +'    <i class="fa fa-plus-circle" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Add row'+ '"></i>' +'  </div>'}
html +=    '</div>';var obj = $(html);obj.data("instance", this);if (!rsb.formPortSettingsForm.readonly) {obj.on("rsb.formPort.deleteRow", onDeleteRow);obj.find(".form-designer-form-icon-add-row").click(onAddRowClick);obj.find(".form-designer-form-icon-add-row i").popover();obj.find(".form-designer-box-icon-delete i").popover();obj.find(".form-designer-box-icon-delete").click(onDeleteBox)}
var boxTitleInput = obj.find(".form-designer-box-title-name");boxTitleInput.val(this.label);if (!rsb.formPortSettingsForm.readonly) {boxTitleInput.on("blur", function() {var form = $(this.closest(".form-designer-form")).data("instance");var value = rsb.formPortSettingsForm.designer.checkXML(this.value);form.name = value;form.label = value;this.value = value});boxTitleInput.keydown(function(e) {if (e.keyCode == 13) {boxTitleInput.blur()}})} else {boxTitleInput.prop("readonly", true)}
var rowContainer = obj.find(".form-designer-row-container");if (this.boxes.length < 1) {var newBox = new Box();newBox.type = "section";this.boxes.push(newBox)}
obj.find(".form-designer-box").data("instance", this.boxes[0]);this.boxes[0].getRows().forEach(function($row) {if (!($row.getFields().length > 0 && $row.getFields()[0].type == "section")) {rowContainer.append($row.getUI())}});return obj}
this.getJSON = function() {var formJSON = {"name": this.name,"label": this.label,"index": this.index,"minOccurs": this.minOccurs,"maxOccurs": this.maxOccurs,"index": this.index,"forms": [],"fields": []};for (var i in this.boxes) {if (this.boxes[i].type == "section") {var sectionJSON = this.boxes[i].getJSON();sectionJSON.fields.forEach(function($elem) {formJSON.fields.push($elem)})} else {var subformJSON = this.boxes[i].getJSON();subformJSON.forms.forEach(function($elem) {formJSON.forms.push($elem)})}}
return formJSON}
this.getUserView = function() {var html = '<div class="form-userview-form">' +'  <div class="row"><div class="col-md-12"><h1 class="page-header"></h1></div></div>' +'  <input type="hidden" class="input-form-name">' +'</div>';var obj = $(html);obj.find("h1").text(this.label);obj.find("input").attr("value", this.name);for (var i in this.boxes) {if (this.boxes[i].type == "section") {obj.append(this.boxes[i].getUserView())} else {var subform = this.boxes[i].getSubform().getFormTemplate();if (subform.getInsideFields().length > 0) {obj.append(this.boxes[i].getUserView())}}}
return obj}
this.getDataJSON = function() {var dataArray = [];this.boxes.forEach(function($elem) {var boxData = $elem.getDataJSON();for (var i in boxData) {dataArray.push(boxData[i])}});var dataJSON = {};dataJSON[this.name] = dataArray;return dataJSON}
this.getAllFields = function() {var allFields = this.getInsideFields();this.boxes.forEach(function($elem) {if ($elem.type != "section") {$elem.getSubform().getFormTemplate().getAllFields().forEach(function($field) {if (!allFields.includes($field)) {allFields.push($field)}})}});return allFields}
this.isEmptyForm = function() {var fields = this.getAllFields();var isEmpty = true;for (var i = 0; i < fields.length; i++) {if (fields[i].value) {isEmpty = false;break}}
return isEmpty}
this.getInsideFields = function() {var insideFields = [];for (var i in this.boxes) {if (this.boxes[i].type == "section") {this.boxes[i].getInsideFields().forEach(function($elem) {insideFields.push($elem)})}}
return insideFields}
this.getSubformByName = function($name) {for (var i in this.boxes) {if (this.boxes[i].type == "detail" && this.boxes[i].getSubform() && this.boxes[i].getSubform().getFormTemplate().name == $name) {return this.boxes[i].getSubform()}}
return null}
this.addForm = function ($form) {var newBox = new Box();newBox.type = "detail";newBox.addSubform($form);this.boxes.push(newBox)}
this.addSubform = function($subForm) {var newBox = new Box();newBox.type = "detail";newBox.setSubform($subForm.copy());this.boxes.push(newBox)}
this.addSection = function($section) {var section = new Field();section.label = $section;section.name = "Section_" + $section;section.type = "section";section.width = 12;section.index = this.boxes.length;var newBox = new Box();newBox.type = "section";var newRow = new Row();newRow.addField(section);newBox.addRow(newRow);newBox.addRow();this.boxes.push(newBox)}
this.removeBox = function($box) {var index = this.boxes.indexOf($box);this.boxes.splice(index, 1)}
this.isIncludeField = function($field) {var isIncludeField = false;for (var i in this.boxes) {if (this.boxes[i].type == "section") {var insideFields = this.boxes[i].getInsideFields();if (insideFields.includes($field)) {isIncludeField = true;break}}}
return isIncludeField}
this.checkSameElement = function($name) {return (this.getSubformByName($name) || this.getFieldByName($name)) ? true : false}
this.getFieldByName = function($name) {for (var i in this.boxes) {if (this.boxes[i].type == "section") {var insideFields = this.boxes[i].getInsideFields();for (var j in insideFields) {if ($name == insideFields[j].name) {return insideFields[j]}}}}
return null}
this.copy = function($includeValue) {var newForm = new Form(this);for (var i in this.boxes) {newForm.boxes.push(this.boxes[i].copy($includeValue))}
return newForm}
this.parseDataJSON = function($data) {var mapping = false;for (var i in $data) {var name = Object.keys($data[i])[0];var field = this.getFieldByName(name);var subform = this.getSubformByName(name);if (field) {field.value = $data[i][name];mapping = true} else if (subform) {var newForm = subform.getFormTemplate().copy();newForm.parseDataJSON($data[i][name]);subform.addSubform(newForm);mapping = true}}
return mapping}
this.setReadOnly = function($isreadonly) {for (var i in this.boxes) {this.boxes[i].setReadOnly($isreadonly)}
this.readonly = $isreadonly}
this.getIndex = function() {if (this.boxes.length > 0) {if (this.boxes[0].type == "section" && this.boxes[0].getRows().length > 0 && this.boxes[0].getRows()[0].getFields().length > 0) {return this.boxes[0].getRows()[0].getFields()[0].length} else {this.boxes[0].getSubform().getTemplate().getIndex()}}
return 0}
this.updateIndex = function() {for (var i in this.boxes) {this.boxes[i].setIndex(i)}}
this.reset = function() {this.name = ""
this.label = "";this.minOccurs = -1;this.maxOccurs = -1;this.boxes = [];this.readonly = false}
var Row = function() {var DRAG_OPTIONS = {revert: "invalid",zIndex: 100,distance: 10,helper: function($event) {var obj = $($event.currentTarget);var offsetClasses = [];var offset = 0;var classList = obj[0].className.split(" ");classList.forEach(function($elem) {if ($elem.startsWith("col-md-offset-")) {offsetClasses.push($elem)}});for (var i in offsetClasses) {obj.removeClass(offsetClasses[i]);offset = parseInt(offsetClasses[i].substring(14))}
obj.css({left: "" + (obj.closest(".form-designer-row").width() / 12 * offset) + "px"});return obj}};var fields = [];var insertFieldToUI = function($rowObj, $field) {var newFieldUI = $('<div class="form-designer-col original-style"></div>').append($field.getUI());if (!rsb.formPortSettingsForm.readonly) {newFieldUI.draggable(DRAG_OPTIONS);newFieldUI.droppable({"accept": ".form-designer-col","greedy": true,"drop": onDropOnCol})}
var insertObj = null;$rowObj.find(".form-designer-col").each(function() {$(this).removeClass($(this).attr("class").match(/(col-md-\d)/)[0]);$(this).removeClass($(this).attr("class").match(/(col-md-offset-\d)/)[0]);var instance = $(this).children().data("instance");if (instance.offset > $field.offset && insertObj == null) {newFieldUI.insertBefore($(this));insertObj = $(this)}});if (insertObj == null) {$rowObj.append(newFieldUI)}
var currentOffset = 0;$rowObj.find(".form-designer-col").each(function() {var instance = $(this).children().data("instance");$(this).addClass("col-md-" + instance.width);var offset = 0;if (currentOffset < instance.offset) {offset = instance.offset - currentOffset}
$(this).addClass("col-md-offset-" + offset);currentOffset += instance.width;currentOffset += offset})}
var onDelete = function() {rsb.connect.hidePopover(this);var row = $(this).closest(".form-designer-row");if (row.data("instance").getFields().length < 1) {row.trigger("rsb.formPort.deleteRow", [row]);row.remove();rsb.formPortSettingsForm.designer.setUnSaved()} else {rsb.confirmModal({title: 'Remove Row',body: 'This will remove the row and any form fields within it. Are you sure you want to proceed?',ok: function() {row.trigger("rsb.formPort.deleteRow", [row]);row.remove();rsb.formPortSettingsForm.designer.setUnSaved()},cancelText: 'Cancel'});return false}}
var onDrop = function($event, $ui) {var row = $(this);var form = $(this).closest(".form-designer-form").data("instance");var property = {};var apply = function() {property.row = row.closest(".form-designer-row-container").find(".form-designer-row").index(row);property.offset = offset;var newField = new Field(property);row.data("instance").addField(newField);row.replaceWith(row.data("instance").getUI())}
if ($ui.helper.hasClass("list-group-item")) {var width = 0;row.data("instance").getFields().forEach(function($elem) {width += $elem.width});if (width >= 12) {$ui.helper.remove();return}
var offset = ($ui.offset.left - row.offset().left) > (row.width() / 2) ? 6 : 0;var fieldName = $ui.helper.data("name");if (form.checkSameElement(fieldName)) {rsb.formPortPropertyEditor.show([{ "name": "Name", "value": fieldName, "required": true }], function($data) {var name = $data.Name;if (name != rsb.formPortSettingsForm.designer.checkXML(name)) {return 'Invalid XML element name:'+ " " + name}
if (form.checkSameElement(name)) {return 'The form already contains an element with the same name:'+ ' "' + name + '"'}
property.name = name;property.label = name;rsb.formPortSettingsForm.designer.setUnSaved();apply()}, null, 'The form already contains an element with the same name:'+ ' "' + fieldName + '"')} else {rsb.formPortSettingsForm.designer.setUnSaved();property.name = fieldName;property.label = fieldName;apply()}} else if ($ui.helper.hasClass("form-designer-col")) {var col = $ui.helper;var field = col.children().data("instance");var oldRow = col.closest(".form-designer-row");if (form.isIncludeField(field) || !form.checkSameElement(field.name)) {var offset = ($event.clientX - row.offset().left) > (row.width() / 2) ? 6 : 0;var width = 0;row.data("instance").getFields().forEach(function($elem) {width += $elem.width});if (width >= 12) {$ui.helper.remove();oldRow.replaceWith(oldRow.data("instance").getUI())} else {field.offset = offset;field.row = row.closest(".form-designer-row-container").find(".form-designer-row").index(row);if (!row.is(oldRow)) {oldRow.data("instance").removeField(field);oldRow.replaceWith(oldRow.data("instance").getUI());row.data("instance").addField(field)}
row.replaceWith(row.data("instance").getUI());rsb.formPortSettingsForm.designer.setUnSaved()}} else {rsb.showResult(rsb.formPortSettingsForm.resultContainer, 'The form already contains an element with the same name:'+ ' "' + field.name + '"', false);$ui.helper.remove();oldRow.replaceWith(oldRow.data("instance").getUI())}}}
var onDropOnCol = function($event, $ui) {var destCol = $(this);var srcCol = $ui.helper;var destRow = destCol.closest(".form-designer-row");var destForm = destCol.closest(".form-designer-form");var srcRow = srcCol.closest(".form-designer-row");var srcForm = srcCol.closest(".form-designer-form");var destField = destCol.children().data("instance");var destOffset = destField.offset;var destRowIndex = destField.row;var srcField = srcCol.children().data("instance");var srcOffset = srcField.offset;var srcRowIndex = srcField.row;if ((destForm.data("instance").isIncludeField(srcField) || !destForm.data("instance").checkSameElement(srcField.name))
&& (srcForm.data("instance").isIncludeField(destField) || !srcForm.data("instance").checkSameElement(destField.name))) {destField.offset = srcOffset;srcField.offset = destOffset;if (!srcRow.is(destRow)) {destField.row = srcRowIndex;srcField.row = destRowIndex;srcRow.data("instance").removeField(srcField);srcRow.data("instance").addField(destField);srcRow.replaceWith(srcRow.data("instance").getUI());destRow.data("instance").removeField(destField);destRow.data("instance").addField(srcField);destRow.replaceWith(destRow.data("instance").getUI())} else {srcRow.replaceWith(srcRow.data("instance").getUI())}
rsb.formPortSettingsForm.designer.setUnSaved()} else {rsb.showResult(rsb.formPortSettingsForm.resultContainer, 'The form already contains an element with the same name:'+ ' "' + srcField.name + '"/"' + destField.name + '"', false);$ui.helper.remove();srcRow.replaceWith(srcRow.data("instance").getUI())}}
var onFieldDelete = function($event, $fieldObj) {rsb.formPortSettingsForm.designer.setUnSaved();var field = $fieldObj.data("instance");var index = fields.indexOf(field);if (index >= 0) {fields.splice(index, 1)}
var rowObj = $fieldObj.closest(".form-designer-row");rowObj.replaceWith(rowObj.data("instance").getUI());return false}
this.getFields = function(){return fields}
this.addFieldByOption = function($fieldOption) {this.addField(new Field($fieldOption))}
this.addField = function($field) {var insertIndex = fields.length;for (var i in fields) {if (fields[i].offset < $field.offset && fields.length > (i + 1) && fields[parseInt(i) + 1].offset > $field.offset) {insertIndex = i;break}}
fields.splice(insertIndex, 0, $field);fields = fields.sort(function($leftField, $rightField) {return $leftField.offset - $rightField.offset})}
this.removeField = function($field) {var index = fields.indexOf($field);if (index >= 0) {fields.splice(index, 1)}}
this.getUI = function() {var html = '<div class="form-designer-row">';if (!rsb.formPortSettingsForm.readonly) {html +=  '  <div class="form-designer-row-icon form-designer-row-icon-delete">' +'    <i class="fa fa-minus-circle" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="left" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Remove row'+ '"></i>' +'  </div>'}
html +=    '</div>';obj = $(html);obj.data("instance", this);if (!rsb.formPortSettingsForm.readonly) {obj.on("rsb.formPort.deleteField", onFieldDelete);obj.find(".form-designer-row-icon-delete").click(onDelete);obj.find(".form-designer-row-icon-delete i").popover();obj.droppable({"accept": ".form-source .list-group-item, .form-designer-col","greedy": true,"drop": onDrop})}
fields.forEach(function($elem) {if ($elem.type != "section") {insertFieldToUI(obj, $elem)}});return obj}
this.getUserView = function() {var obj = $("<div class='row'></div>");var currentOffset = 0;if (fields.length > 0) {fields = fields.sort(function($leftField, $rightField) {return $leftField.offset - $rightField.offset});fields.forEach(function($elem) {var fieldObj = $elem.getUserView();fieldObj.addClass("col-md-" + $elem.width);var offset = 0;if (currentOffset < $elem.offset) {offset = $elem.offset - currentOffset}
fieldObj.addClass("col-md-offset-" + offset);currentOffset += $elem.width;currentOffset += offset;obj.append(fieldObj)})} else {obj.addClass("form-userview-emptyrow")}
return obj}
this.copy = function($includeValue) {var newRow = new Row();for (var i in fields) {newRow.getFields().push(fields[i].copy($includeValue))}
return newRow}
this.setReadOnly = function($isreadonly) {for (var i in fields) {fields[i].setReadOnly($isreadonly)}}}
var Box = function() {var DRAG_OPTIONS = {revert: "invalid",containment: "document",zIndex: 100,distance: 10,cancel: ".form-designer-row-container, .form-designer-form-icon, .form-designer-box-title-name",helper: function($event) {var obj = $($event.currentTarget);return obj}};var onDropOnBox = function($event, $ui) {var destBox = $(this);var srcBox = $ui.helper;var form = destBox.closest(".form-designer-form");var destIndex = form.data("instance").boxes.indexOf(destBox.data("instance"));var srcIndex = form.data("instance").boxes.indexOf(srcBox.data("instance"));var movedBox = srcBox.data("instance");form.data("instance").boxes.splice(srcIndex, 1);form.data("instance").boxes.splice(destIndex, 0, movedBox);form.data("instance").updateIndex();form.replaceWith(form.data("instance").getUI())}
this.type = "";var rows = [];var subform = null;this.getRows = function() {return rows}
this.addSubform = function($form) {var newSubform = new Subform();newSubform.setFormTemplate($form);subform = newSubform}
this.setSubform = function($subForm) {subform = $subForm}
this.getSubform = function() {return subform}
this.addFormByOption = function($formOption) {subform = new Subform();subform.addFormByOption($formOption)}
this.getUI = function() {var obj;if (this.type == "detail") {var html = '<div class="form-designer-box"></div>';obj = $(html);obj.data("instance", this);obj.append(subform.getFormTemplate().getUIAsSubForm())} else {var html = '<div class="form-designer-box">' +'  <div class="form-designer-box-title form-validate-error-container">' +'    <input type="text" name="section' + rsb.securityRand() + '" class="form-designer-box-title-name rsb-form-nosubmit" required>' +'  </div>';if (!rsb.formPortSettingsForm.readonly) {html +=  '  <div class="form-designer-form-icon form-designer-box-icon-delete">' +'    <i class="fa fa-times" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="left" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Remove section'+ '"></i>' +'  </div>'}
html +=    '  <div class="form-designer-row-container">' +'  </div>';if (!rsb.formPortSettingsForm.readonly) {html +=  '  <div class="form-designer-form-icon form-designer-form-icon-add-row">' +'    <i class="fa fa-plus-circle" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Add row'+ '"></i>' +'  </div>'}
html +=    '</div>';obj = $(html);obj.data("instance", this);if (!rsb.formPortSettingsForm.readonly) {obj.on("rsb.formPort.deleteRow", onDeleteRow);obj.find(".form-designer-box-icon-delete").click(onDeleteBox);obj.find(".form-designer-form-icon-add-row").click(onAddRowClick);obj.find(".form-designer-form-icon-add-row i").popover();obj.find(".form-designer-box-icon-delete i").popover()}
var rowsContainer = obj.find(".form-designer-row-container");var section = "";rows.forEach(function($elem) {if ($elem.getFields().length > 0 && $elem.getFields()[0].type == "section") {section = $elem.getFields()[0].label} else {rowsContainer.append($elem.getUI())}});var sectionTitleInput = obj.find(".form-designer-box-title-name");sectionTitleInput.val(section);if (!rsb.formPortSettingsForm.readonly) {sectionTitleInput.on("blur", function() {var sectionField = $(this.closest(".form-designer-box")).data("instance").getRows()[0].getFields()[0];sectionField.name = "Section_" + this.value;sectionField.label = this.value});sectionTitleInput.keydown(function(e) {if (e.keyCode == 13) {sectionTitleInput.blur()}});obj.draggable(DRAG_OPTIONS);obj.droppable({"accept": ".form-designer-box","greedy": true,"drop": onDropOnBox})} else {sectionTitleInput.prop("readonly", true)}}
return obj}
this.getJSON = function() {var json = { "fields": [], "forms": [] };if (subform) {if (subform.getForms().length > 0) {var forms = subform.getForms();forms.forEach(function($elem) {json.forms.push($elem.getJSON())})} else {json.forms.push(subform.getFormTemplate().getJSON())}} else {rows.forEach(function($elem) {$elem.getFields().forEach(function($field) {json.fields.push($field.getJSON())})})}
return json}
this.getUserView = function() {var obj = $("<div class='row'></div>");if (rows.length > 0) {rows.forEach(function($elem) {obj.append($elem.getUserView())})}
if (subform) {obj.append(subform.getUserView())}
if (rows.length < 1 && subform == null) {obj = $('<div class="placeholder-row">&nbsp;</div>')}
return obj}
this.getDataJSON = function() {var dataJSON = [];if (rows.length > 0) {rows.forEach(function($elem) {$elem.getFields().forEach(function($field) {if ($field.type != "section") {dataJSON.push($field.getDataJSON())}})})}
if (subform) {dataJSON.push(subform.getDataJSON())}
return dataJSON}
this.getInsideFields = function() {var insideFields = [];for(var i in rows) {rows[i].getFields().forEach(function($elem) {if ($elem.type != "section") {insideFields.push($elem)}})}
return insideFields}
this.copy = function($includeValue) {var newBox = new Box();for (var i in rows) {newBox.type = "section";newBox.getRows().push(rows[i].copy($includeValue))}
if (subform) {newBox.type = "detail";var newSubform = subform.copy($includeValue);newBox.setSubform(newSubform)}
return newBox}
this.setReadOnly = function($isreadonly) {for (var i in rows) {rows[i].setReadOnly($isreadonly)}
if (subform) {subform.setReadOnly($isreadonly)}}
this.addRow = function($row) {if ($row) {rows.push($row)} else {rows.push(new Row())}}
this.getIndex = function() {var index = undefined;if (this.type == "section" && this.rows.length > 0 && this.rows[0].getFields().length > 0) {index = this.rows[0].getFields()[0].index} else {index = subform.getFormTemplate().index}
return index}
this.setIndex = function($index) {if (this.type == "section") {if (rows.length > 0 && rows[0].getFields().length > 0 && rows[0].getFields()[0].type == "section") {rows[0].getFields()[0].index = $index}} else {subform.getFormTemplate().index = $index}}
this.deleteRow = function($row) {var tempRows;if (rows.includes($row)) {tempRows = rows} else {tempRows = subform.getFormTemplate().boxes[0].getRows()}
var index = tempRows.indexOf($row);tempRows.splice(index, 1);for (var i = index; i < tempRows.length; i++) {tempRows[i].getFields().forEach(function($field){$field.row = $field.row - 1})}}
var Subform = function() {var formTemplate = null;var subforms = [];var onAddNewLineClick = function() {var table = $(this).closest(".table-container");var dataContainer = table.find("table");var subform = table.data("instance");var newForm = subform.getFormTemplate().copy();var currentOccurs = dataContainer.find("tbody").find("tr.subform-row").length;if (newForm.maxOccurs < 1 || currentOccurs < newForm.maxOccurs) {appendLine(dataContainer, newForm, true);subform.addSubform(newForm)}}
var onDeleteLineClick = function() {var btn = $(this);var table = btn.closest(".table-container");rsb.confirmModal({title: 'Delete Line',body: 'This will remove the data from the form. Are you sure you want to proceed?',ok: function() {var subform = table.data("instance");var dataContainer = table.find("table");var index = btn.closest(".subform-row")[0].rowIndex;var data = dataContainer.find("tr:eq(" + index + ")").data("instance");subform.getForms().splice(subform.getForms().indexOf(data), 1);if (dataContainer.find("tr:eq(" + (index + 1) + ")").hasClass("inside-template")) {dataContainer.find("tr:eq(" + (index + 1) + ")").remove()}
dataContainer.find("tr:eq(" + index + ")").remove()},cancelText: 'Cancel'});return false}
var onValueChange = function() {$(this).data("instance").value = $(this).val();$(this).closest("td").find("span").text($(this).val())}
var onShowEditCell = function() {var inputObj = $(this).find("input");if (inputObj.hasClass("hidden")) {$(this).closest(".subform-row").addClass("subform-row-editing");$(this).find("span").addClass("hidden");var value = inputObj.val();inputObj.removeClass("hidden").focus();inputObj.val("").val(value)}}
var onHiddenEditCell = function() {$(this).closest(".subform-row").removeClass("subform-row-editing");$(this).addClass("hidden");$(this).closest("td").find("span").removeClass("hidden")}
var appendLine = function($table, $form){var line = "";line += "<tr class='subform-row'>";var insideFields = $form.getInsideFields();for (var i in insideFields) {var f = $form.getFieldByName(insideFields[i].name);line += "<td><div class='has-feedback'><span class='hidden'>" + ((f && f.value) ? f.value : "&nbsp;") + "</span><input type='text' class='form-control form-data-input rsb-form-nosubmit' " + ((f && f.readonly) ? "readonly" : "") + " value='" + ((f && f.value) ? f.value : "") + "' savedvalue='" + ((f && f.value) ? f.value : "") + "'></div></td>"}
line += "</tr>";var lineObj = $(line);lineObj.find("td:last div.has-feedback").append('<div style="right: 0;" class="form-userview-row-icon form-userview-row-icon-delete pull-right form-control-feedback"><i class="fa fa-minus-circle" aria-hidden="true"></i></div>');$table.children("tbody").append(lineObj[0]);var newLine = $table.find("tbody tr.subform-row:last");newLine.data("instance", $form);newLine.addClass($table.children("tbody").children("tr").length % 2 == 0 ? "even" : "odd");for (var i in insideFields) {var cell = newLine.find("td:eq(" + i + ")");var fieldInput = cell.find("input");fieldInput.data("instance", insideFields[i]);fieldInput.change(onValueChange)}
newLine.find(".form-userview-row-icon-delete").click(onDeleteLineClick)}
this.getForms = function() {return subforms}
this.setFormTemplate = function($form) {formTemplate = $form}
this.getFormTemplate = function() {return formTemplate}
this.addFormByOption = function($formOption) {formTemplate = new Form($formOption)}
this.addSubform = function($form) {subforms.push($form)}
this.getUserView = function() {if (formTemplate) {if (formTemplate.maxOccurs != 1) {var htmlTable =  '<div class="col-md-12">' +'  <h3 class="page-header"></h3>' +'  <input type="hidden" class="input-form-name">' +'  <div class="form-group row mb-3">' +'    <div class="table-container col-md-12">' +'      <table class="table form-userview-subform-table table-hover table-bordered table-striped table-condensed dataTable" width="100%">' +'        <thead>' +'          <tr>';var insideFields = formTemplate.getInsideFields();for (var i in insideFields) {htmlTable +=   '            <th>' + insideFields[i].label + '</th>'}
htmlTable +=     '          </tr>' +'        </thead>' +'        <tbody></tbody>' +'      </table>'
if (!formTemplate.readonly) {htmlTable +=   '      <div class="form-userview-table-icon-add-row"><i class="fa fa-plus-circle" aria-hidden="true"></i></div>'}
htmlTable +=     '    </div>' +'  </div>' +'</div>';var obj = $(htmlTable);obj.find(".table-container").data("instance", this);obj.find("h3").text(formTemplate.label);obj.find("input").attr("value", formTemplate.name);var table = obj.find(".table-container table");if (subforms.length > 0) {for (var i in subforms) {appendLine(table, subforms[i], true)}} else {var newSubform = formTemplate.copy();subforms.push(newSubform);appendLine(table, newSubform, true)}
if (!formTemplate.readonly) {obj.find(".form-userview-table-icon-add-row:last").click(onAddNewLineClick)}
return obj} else {return formTemplate.getUserView()}}}
this.getDataJSON = function() {var dataJSON = [];subforms.forEach(function($elem) {if (!$elem.isEmptyForm()) {dataJSON.push($elem.getDataJSON())}});return dataJSON}
this.copy = function($includeValue) {var newSubform = new Subform();newSubform.setFormTemplate(formTemplate.copy(false));if ($includeValue) {for (var i in subforms) {newSubform.addSubform(subforms[i].copy(true))}}
return newSubform}
this.setReadOnly = function($isreadonly) {formTemplate.setReadOnly($isreadonly);for (var i in subforms) {subforms[i].setReadOnly($isreadonly)}}}}
$form = $form || {};this.name = $form.name || this.name;this.label = $form.label || this.label;this.minOccurs = $form.minOccurs || this.minOccurs;this.maxOccurs = $form.maxOccurs || this.maxOccurs;this.index = $form.index != undefined ? $form.index : this.index;if ($form.fields) {for (var i in $form.fields) {var field = $form.fields[i];if (field.type == "section") {while (this.boxes.length <= field.index) {this.boxes.push(new Box())}
var newSectionBox = this.boxes[field.index];newSectionBox.type = "section";newSectionBox.addRow();newSectionBox.getRows()[0].addFieldByOption(field)} else {var lastSectionIndex = 0;if (this.boxes.length > 0) {for (var boxIndex = this.boxes.length - 1; boxIndex >= 0; boxIndex--) {if (this.boxes[boxIndex].type == "section") {lastSectionIndex = boxIndex;break}}} else {var sectionBoxInSubform = new Box();sectionBoxInSubform.type = "section";this.boxes.push(sectionBoxInSubform)}
var rowIndex = field.row;if (this.boxes[lastSectionIndex].getRows().length > 0 && this.boxes[lastSectionIndex].getRows()[0].getFields().length > 0
&&  this.boxes[lastSectionIndex].getRows()[0].getFields()[0].type == "section") {rowIndex++}
while(this.boxes[lastSectionIndex].getRows().length <= rowIndex) {this.boxes[lastSectionIndex].addRow()}
this.boxes[lastSectionIndex].getRows()[rowIndex].addFieldByOption(field)}}}
if ($form.forms) {for (var i in $form.forms) {var form = $form.forms[i];if (form.index == undefined) {form.index = this.boxes.length}
while (this.boxes.length <= form.index) {this.boxes.push(new Box())}
this.boxes[form.index].type = "detail";this.boxes[form.index].addFormByOption(form)}}}
var FormSet = function($formSet) {var forms = [];var template = undefined;var formFields = [];var insertFormToUI = function($formSetObj, $form) {var insertIndex = forms.indexOf($form);if (insertIndex >= 0) {var formContainer = $formSetObj.find(".form-designer-form-container");var existingFormObj = formContainer.find(".form-designer-form-container-row").eq(insertIndex);if (existingFormObj.length > 0) {existingFormObj.before($form.getUI())} else {formContainer.append($form.getUI())}}}
var onFormDelete = function($event, $formObj) {var form = $formObj.data("instance");var index = forms.indexOf(form);if (index >= 0) {forms.splice(index, 1)}
$formObj.closest(".form-designer-form-container-row").remove()}
this.listForms = function() {return forms}
this.getTemplate = function() {return template}
this.setTemplate = function($template) {template = $template}
this.removeFormField = function($name) {if (formFields.includes($name)) {formFields.splice(formFields.indexOf($name), 1)}}
this.pushFormField = function($name) {if (!formFields.includes($name)) {formFields.push($name)}}
this.getFormFields = function() {return formFields}
this.getUI = function() {var obj = $('<div class="form-designer-formset"><div class="form-designer-form-container"></div></div>');obj.data("instance", this);if (!rsb.formPortSettingsForm.readonly) {obj.on("rsb.formPort.deleteForm", onFormDelete)}
forms.forEach(function($elem) {insertFormToUI(obj, $elem)});return obj}
this.getJSON = function() {var json = { "template": this.getTemplate(), "forms": [], "formFields":[] };forms.forEach(function($elem) {var formJSON = $elem.getJSON();json.forms.push(formJSON)});formFields.forEach(function($elem) {json.formFields.push($elem)})
return json}
this.getUserView = function() {var obj = $([]);forms.forEach(function($elem) {obj = obj.add($elem.getUserView())});return obj}
this.getDataJSON = function() {var dataJSON = {};dataJSON["Items"] = [];forms.forEach(function($elem) {dataJSON["Items"].push($elem.getDataJSON())});return dataJSON}
this.parseDataJSON = function($data) {var notMatching = false;var formsData = JSON.parse($data)["Items"];var parsedForms = [];for (var i in formsData) {var formData = formsData[i];var formName = Object.keys(formData)[0];var existingForm = null;for (var j in forms) {if (forms[j].name == formName) {existingForm = forms[j];break}}
if (existingForm != null) {var form = existingForm;if (parsedForms.indexOf(formName) > -1) {form = existingForm.copy();forms.push(form)}
notMatching = !form.parseDataJSON(formData[formName]);parsedForms.push(formName)} else {notMatching = true}}
if (notMatching) {return  'Unable to find a matching form name.'}}
this.setReadOnly = function($isreadonly) {for (var i in forms) {forms[i].setReadOnly($isreadonly)}}
if ($formSet && $formSet.forms) {for (var i in $formSet.forms) {forms.push(new Form($formSet.forms[i]))}}
if ($formSet && $formSet.template) {template = $formSet.template}
if ($formSet && $formSet.formFields) {for (var i in $formSet.formFields) {formFields.push($formSet.formFields[i])}}}
var Designer = function() {var _ui = {};_ui.designer = $("#formConnectorSettingsForm .form-designer");_ui.designerIsSaved = $("#formConnectorSettingsForm #formportsettings_form_issaved");_ui.addDetailBtn = _ui.designer.find(".btn-add-detail");_ui.addSectionBtn = _ui.designer.find(".btn-add-section");_ui.formSetContainer = _ui.designer.find(".form-designer-formset-container");var formSet = null;var setUnSaved = function() {_ui.designerIsSaved.val("unSaved")}
var onAddDetailClick = function() {var property = {};var apply = function() {var form = _ui.formSetContainer.find(".form-designer-form:first");var newform = new Form();newform.name = property.name;newform.label = property.label;newform.index = form.data("instance").boxes.length;newform.addSubformBox();form.data("instance").addForm(newform);form.replaceWith(form.data("instance").getUI());setUnSaved()}
rsb.formPortPropertyEditor.show([{ "name": "Detail", "required": true }], function($data) {property.label = rsb.htmlEncode($data.Detail);property.name = rsb.formPortSettingsForm.designer.checkXML(property.label);if (formSet.listForms()[0].checkSameElement(property.name)) {return 'The form already contains an element with the same name:'+ ' "' + property.name + '"'}
apply()}, null, null, 'Add Detail')}
var onAddSectionClick = function() {setUnSaved();var property = {};var apply = function() {var form = _ui.formSetContainer.find(".form-designer-form:first");form.data("instance").addSection(property.name);form.replaceWith(form.data("instance").getUI())}
rsb.formPortPropertyEditor.show([{ "name": "Section", "required": true }], function($data) {property.name = rsb.htmlEncode($data.Section);apply()}, null, null, 'Add Section')}
this.load = function($workspace, $connectorId, $template, $errorContainer) {_ui.formSetContainer.empty();formSet = new FormSet();var designer = this;$.ajax({url: "src/formGetForm.rsb",type: "POST",data: { "@json": true, "connectorid": $workspace + ":" + $connectorId, "template": $template },dataType: "json"}).done(function(data, textStatus, jqXHR) {data = data["items"];var errorMsg = rsb.getResultErrorMessage(data);if (errorMsg) {rsb.showResult($errorContainer, errorMsg, false)} else if (data[0] && data[0]["form"]) {formSet = new FormSet(JSON.parse(data[0]["form"]).formSet)} else {formSet.listForms().push(new Form())}
rsb.formPortSettingsForm.source.load(rsb.formPortSettingsForm.workspace, rsb.formPortSettingsForm.portId, "", rsb.formPortSettingsForm.resultContainer)}).always(function() {_ui.formSetContainer.data("instance", designer);_ui.formSetContainer.append(formSet.getUI())})}
this.getFormSet = function() {return formSet}
this.getFormJSON = function() {var json = { "formSet": formSet.getJSON() };return json}
this.setUnSaved = function() {setUnSaved()}
this.isSaved = function() {return _ui.designerIsSaved.val() != "unSaved"}
this.checkXML = function($xml) {var startRegex = /^([^:_A-Za-z])/;var regex = /[^-.:_A-Za-z0-9]/g;var value = "";if ($xml) {value = $xml.replace(startRegex, "_$1").replace(regex, "_")}
return value}
this.getCurrentForm = function() {return formSet.listForms()[0]}
this.updateFieldUI = function($name, $oldname) {if ($name != $oldname) {var fields = _ui.formSetContainer.find(".form-designer-item");for (var i = 0; i < fields.length; i++) {var field = $(fields[i]).data("instance");if (field.name == $oldname) {field.name = $name;$(fields[i]).replaceWith(field.getUI())}}
formSet.removeFormField($oldname);formSet.pushFormField($name)}}
this.deleteFieldUI = function($name) {if ($name) {var rows = _ui.formSetContainer.find(".form-designer-row");for (var i = 0; i < rows.length; i++) {var row = $(rows[i]).data("instance");var fields = row.getFields();for (var j = 0; j < fields.length; j++) {if (fields[j].name == $name) {row.getFields().splice(row.getFields().indexOf(fields[j]), 1);$(rows[i]).replaceWith(row.getUI());break}}}}}
_ui.addDetailBtn.click(onAddDetailClick);_ui.addSectionBtn.click(onAddSectionClick)}
var Source = function() {var DRAG_OPTIONS = {revert: "invalid",containment: "document",zIndex: 100,distance: 10,helper: function($event) {var obj = $($event.currentTarget);var name = obj.data("name");var label = obj.data("label");return obj.clone().text(label).width(obj.outerWidth()).data("name", name).data("label", label)[0]}};var _ui = {};_ui.container = $(".form-source");_ui.fieldList = _ui.container.find(".fields-group");var onFlowPortSettingsResize = function() {updatePosition()}
var updatePosition = function() {_ui.container.css("left", _ui.container.parent().offset().left + "px")}
var onEdit = function() {var obj = $(this).closest("li");var oldName = obj.data("name");rsb.formPortPropertyEditor.show([{ "name": "Name", "value": oldName, "required": true }], function($data) {var name = $data.Name;if (name != rsb.formPortSettingsForm.designer.checkXML(name)) {return 'Invalid XML element name:'+ " " + name}
if (name != oldName && _ui.fieldList.find("li[name='" + name + "']").length > 0) {return 'This element name already exists in the Form Fields list:&nbsp;'+ '"' + name + '"'}
obj.data("name", name).attr("title", name).attr("name", name);obj.find("span").text($data.Name);rsb.formPortSettingsForm.designer.updateFieldUI(name, oldName)})}
var onDelete = function() {rsb.connect.hidePopover($(this).closest("li"));rsb.formPortSettingsForm.designer.setUnSaved();var name = $(this).closest("li").data("name");rsb.formPortSettingsForm.designer.deleteFieldUI(name);rsb.formPortSettingsForm.designer.getFormSet().removeFormField(name);$(this).closest("li").remove()}
var createNewField = function() {if (!_ui.newFieldInput) _ui.newFieldInput = _ui.fieldList.find(".new-field-input");if (!_ui.newFieldDrag) _ui.newFieldDrag = _ui.fieldList.find(".new-field-drag");if (_ui.newFieldInput.val()) {var labelValue = _ui.newFieldInput.val();var newName = rsb.formPortSettingsForm.designer.checkXML(labelValue);if (_ui.fieldList.find("li[name='" + newName + "']").length > 0) {rsb.formPortPropertyEditor.show([{ "name": "Name", "value": newName, "required": true }], function($data) {var name = $data.Name;if (name != rsb.formPortSettingsForm.designer.checkXML(name)) {return 'Invalid XML element name:'+ " " + name}
if (rsb.formPortSettingsForm.designer.getCurrentForm().checkSameElement(name)) {return 'The form already contains an element with the same name:'+ ' "' + name + '"'}
insertFieldObjToList(name)}, null, 'The form already contains an element with the same name:'+ ' "' + newName + '"', 'Edit Form Field:')} else {insertFieldObjToList(newName)}}
_ui.newFieldDrag.removeClass("hidden");_ui.newFieldInput.remove()}
var insertFieldObjToList = function($name, $fromTemplate) {var inputhtml = '<input class="list-group-item list-group-item-field-input hidden" value="' + $name + '"/>';var html = '<li class="list-group-item" title="' + $name + '" name="' + $name + '"><span>' + $name + '</span>';if (!rsb.formPortSettingsForm.readonly) {if (!$fromTemplate) {html +=    '<i class="fa fa-edit form-source-icon-edit" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="left" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Edit field'+ '"></i>' +'<i class="fa fa-trash-o form-source-icon-delete" aria-hidden="true" data-bs-toggle="popover" data-bs-placement="left" data-bs-html="true" data-bs-trigger="hover" data-bs-content="' + 'Delete field'+ '"></i>'}}
html +=    '</li>';var obj = $(html).data("name", $name);if (!rsb.formPortSettingsForm.readonly) {obj.draggable(DRAG_OPTIONS);if (!$fromTemplate) {var inputObj = $(inputhtml);var oldname;inputObj.on("blur", function(){var name = $(this).val();var spanObj = $(this).next("li").find("span");if (name && name != oldname) {var labelValue = name;var newName = rsb.formPortSettingsForm.designer.checkXML(labelValue);var obj = $(this);if (_ui.fieldList.find("li[name='" + newName + "']").length > 0) {obj.val(oldname).addClass("hidden");obj.next("li").removeClass("hidden")
rsb.formPortPropertyEditor.show([{ "name": "Name", "value": newName, "required": true }], function($data) {name = $data.Name;if (name != rsb.formPortSettingsForm.designer.checkXML(name)) {return 'Invalid XML element name:'+ " " + name}
if (rsb.formPortSettingsForm.designer.getCurrentForm().checkSameElement(name)) {return 'The form already contains an element with the same name:'+ ' "' + name + '"'}
obj.next("li").data("name", name).attr("title", name).attr("name", name);spanObj.text(name);rsb.formPortSettingsForm.designer.updateFieldUI(name, oldname)}, null, 'The form already contains an element with the same name:'+ ' "' + newName + '"', 'Edit Form Field:')} else {name = newName;obj.addClass("hidden");obj.next("li").data("name", name).attr("title", name).attr("name", name).removeClass("hidden");spanObj.text(name);rsb.formPortSettingsForm.designer.updateFieldUI(name, oldname)}} else {$(this).next("li").removeClass("hidden");$(this).val(spanObj.text()).addClass("hidden")}});inputObj.keydown(function(e) {if (e.keyCode == 13) {inputObj.blur()}});obj.find(".form-source-icon-edit").click(onEdit);obj.find(".form-source-icon-delete").click(onDelete);obj.find(".form-source-icon-edit").popover();obj.find(".form-source-icon-delete").popover();obj.find("span").click(function() {$(this).closest("li").addClass("hidden");inputObj.removeClass("hidden").focus();oldname = inputObj.val();inputObj.val("").val(oldname)});inputObj.data("instance", rsb.formPortSettingsForm.designer.getCurrentForm().getFieldByName($name));_ui.newFieldDrag.before(inputObj)}}
_ui.newFieldDrag.before(obj);rsb.formPortSettingsForm.designer.getFormSet().pushFormField($name)}
var updateListFunc = function($currentForm) {$currentForm.getInsideFields().forEach(function($elem) {if (_ui.fieldList.find("li[name='" + $elem.name + "']").length < 1) {insertFieldObjToList($elem.name)}})}
this.load = function($workspace, $connectorId, $template, $errorContainer) {_ui.fieldList.empty();_ui.fieldList.append($('<li class="list-group-item list-group-item-field-input new-field-drag" style="cursor:pointer;"><i class="fa fa-plus"></i> ' + 'New Field'+ '</li>'));_ui.newFieldDrag = _ui.fieldList.find(".new-field-drag");if (!rsb.formPortSettingsForm.readonly) {_ui.newFieldDrag.on("click", function(){_ui.newFieldDrag.before($('<input class="list-group-item list-group-item-field-input new-field-input" style="color:black; width:100%;">'));_ui.newFieldDrag.addClass("hidden");_ui.newFieldInput = _ui.fieldList.find(".new-field-input");_ui.newFieldInput.focus();_ui.newFieldInput.on("blur", function(){createNewField()});_ui.newFieldInput.keydown(function(e) {if (e.keyCode == 13) {_ui.newFieldInput.blur()}})})} else {_ui.newFieldDrag.addClass("hidden")}
var fields = rsb.formPortSettingsForm.designer.getFormSet().getFormFields();fields.forEach(function($elem) {insertFieldObjToList($elem)})}
this.updateList = function($currentForm) {updateListFunc($currentForm)}
_ui.container.on("affix.bs.affix", updatePosition);$(document).on("rsb.flow.resizePortSettings", onFlowPortSettingsResize)}
