rsb.batchModal = rsb.batchModal || {};rsb.batchModal.init = false;rsb.batchModal.batchTable = $("#batchInfoTable");rsb.batchModal.updatePostData = {};rsb.batchModal.renderFilenameLink = function(filename) {return "<a href='javascript:void(0);'><span data-bs-toggle='tooltip' data-bs-placement='top'>" + rsb.htmlEncode(filename) + "</span></a>"}
rsb.messageInfo = function () {var CONST_HEADER_ROW = "<div class='row message-header-row'>" +"    <label class='col-md-3'>$name$</label>" +"    <div class='col-md-9'><span class='message-info-text'>$value$</span></div>" +"</div>";var CONST_KNOWN_HEADERS = ["content-type", "processed"];var _modal = $("#messageInfoModal");var _title = _modal.find(".modal-title");var _groupPanel = _modal.find(".group-message-panel");var _generalPanel = _modal.find(".general-message-panel");var _resultContainer = _modal.find(".modal-body>div.alert");var _btnContainer = _modal.find(".btn-container");var _btnBack = _btnContainer.find(".btn.btn-back");var _btnDownloadLog = _btnContainer.find(".btn.btn-download-log");var _btnDownloadMessage = _btnContainer.find(".btn.btn-download-message");var _batchFilter = null;var _showMessageInfo = function ($logEntity, $isBatchMessage) {_resultContainer.hide();var $isBatchGroup = rsb.getValueAsBool($logEntity.isbatchgroup, false);var $container = $isBatchGroup ? _groupPanel : _generalPanel;_resetContainer($container);_resetButtons($isBatchMessage);_title.text('Message Info');if ($isBatchGroup) {_title.text('Batch Group Info')} else {$isBatchMessage && _title.text('Batch Message Info')}
var $postData = $.extend({"@json": true, "checklog": true}, $logEntity);$postData.workspaceid = $logEntity.workspace || $logEntity.workspaceid;if (!!$logEntity.subfolder) {$postData.filename = $logEntity.filename.replace($logEntity.subfolder, '').replace(/^\//, '')} else {$postData.filename = $logEntity.filename;if ($logEntity.filename.length > $postData.filename.length) {$postData.subfolder = $logEntity.filename.substring(0, $logEntity.filename.length - $postData.filename.length)}}
$postData.source = $logEntity.source || "Log";rsb.forEach(["messageid", "filename"], function ($name) {if (!!$postData[$name]) {$container.find(".message-header-row." + $name).show().find(".message-info-text").text($postData[$name])}});if ($isBatchGroup) {$postData.includebatchmessages = "true";_generalPanel.hide();_modal.addClass("batch-info-modal")} else {_groupPanel.hide();_modal.removeClass("batch-info-modal")}
$container.show();$.ajax({dataType: "json",url: "src/getMessageInfo.rsb?" + rsb.securityRand(),type: "POST",data: $postData,success: function (data, textStatus, jqXHR) {var $info = data["items"];var $errorMsg = rsb.getResultErrorMessage($info);if ($errorMsg) {rsb.showResult(_resultContainer, $errorMsg, "error", false, false, true)} else if ($info.length > 0) {var $haslog = false, $hasMsg = false;for (var index in $info) {if ($info[index]["haslog"] && $info[index]["haslog"].toLowerCase() == "true") {$haslog = true}
if ($info[index]["hasmsg"] && $info[index]["hasmsg"].toLowerCase() == "true") {$hasMsg = true}
var $name = $info[index]["name"];if (!$name || !$info[index]["value"]) {continue}
if (["messageid", "filename", "message-id"].indexOf($name.toLowerCase()) >= 0) {$name = $name.toLowerCase().replace("-", "");if (!$postData.hasOwnProperty($name)) {$postData[$name] = $info[index]["value"]}
$container.find(".message-header-row." + $name).show().find(".message-info-text").text($postData[$name])} else {var $headerRow = rsb.evalTemplate(CONST_HEADER_ROW, {name: rsb.htmlEncode($name),value: rsb.htmlEncode($info[index]["value"]).split('\r\n').join("<br>")});if (CONST_KNOWN_HEADERS.indexOf($name.toLowerCase()) >= 0) {$container.find(".message-known-headers").show().append($headerRow)} else {$container.find(".message-extra-headers>h5").off("click").on("click", function () {$container.find(".message-extra-headers").toggleClass("collapsed")});$container.find(".message-extra-headers").show().find(".panel-collapse").append($headerRow)}}}
if ($haslog && !$isBatchMessage) {_btnDownloadLog.removeClass("disabled");_btnDownloadLog.attr("href", 'src/downloadLogs.rst?workspaceid=' + encodeURIComponent($postData.workspaceid) + '&connectorid=' + encodeURIComponent($postData.connectorid) + '&direction=' + encodeURIComponent($postData.direction) + '&messageid=' + encodeURIComponent($postData.messageid)).parent().popover("dispose")}
if ($hasMsg) {_btnDownloadMessage.removeClass("disabled");_btnDownloadMessage.attr("href", 'src/downloadMessage.rst?workspaceid=' + encodeURIComponent($postData.workspaceid) + '&connectorid=' + encodeURIComponent($postData.connectorid) + '&direction=' + encodeURIComponent($postData.direction) + '&messageid=' + encodeURIComponent($postData.messageid) + '&filename=' + encodeURIComponent($postData.filename) + '&subfolder=' + encodeURIComponent($postData.subfolder || "") + '&source=' + encodeURIComponent($postData.source) + (!$isBatchGroup && !!$postData.batchgroupid ? '&batchgroupid=' + encodeURIComponent($postData.batchgroupid) : "")).parent().popover("dispose")}}
_modal.modal('show');if ($isBatchGroup) {_initBatchMessagesTable($postData)}}})}
var _initBatchMessagesTable = function () {if (!rsb.batchModal.init) {_modal.on('shown.bs.modal', function () {_groupPanel.find(".batch-messages").show();if (rsb.batchModal.batchTable.DataTable().columns.adjust) {rsb.batchModal.batchTable.DataTable().columns.adjust()}});var options = {scrollX: false,scrollY: "370px",scrollCollapse: true,searching: false,order: [[ 0, 'desc' ]],sDom: "<'row justify-content-between'<'col-md-5'i><'col-md-4 search-bar pull-right'>r>t<'row'<'col-md-2 table-filter'><'col-md-2 nowrap table-length'l><'col-md-8'p>>",lengthMenu: [10, 20, 50, 100],language: {url : 'ui/datatables/lang/'+ 'english.js'},rowCallback: function (row, data) {if (data.status == "Error") {$(row).find("td.status").addClass("text-danger")} else if (data.status == "Warning" || data.status == "Pending") {$(row).find("td.status").addClass("text-warning")} else if (["Success", "Sent", "Received"].indexOf(data.status) >= 0) {$(row).find("td.status").addClass("text-success")}
$(row).find("td.filename").click(data, function ($event) {var messageInfo = {};messageInfo.connectorid = rsb.batchModal.updatePostData.connectorid;messageInfo.workspaceid = rsb.batchModal.updatePostData.workspaceid;messageInfo.direction = rsb.batchModal.updatePostData.direction;messageInfo.batchgroupid = rsb.batchModal.updatePostData.batchgroupid;messageInfo.messageid = ($event || window.event).data.messageid;messageInfo.filename = ($event || window.event).data.filename;messageInfo.source = rsb.batchModal.updatePostData.islog == "true" ? "Log" : "MessageMgr";messageInfo.isbatchgroup = false;_showMessageInfo(messageInfo, true)}).find("[data-bs-toggle='tooltip']").attr("title", "Message Id: " + rsb.htmlEncode(data.messageid)).tooltip()},columns: [{data: "timestamp",render: rsb.formatTimestamp,width: "140px"},{data: "status",width: "80px",className: "status"},{data: "filename",render: rsb.batchModal.renderFilenameLink,className: "filename"},{data: "filesize",render: rsb.connect.formatFileSize,width: "100px"},{data: "messageid",visible: false}
],initComplete: function() {rsb.batchModal.batchTable.closest(".table-container").find("div.table-filter").html('<select class="form-control form-select form-control-sm" onchange="rsb.batchModal.batchTable.DataTable().ajax.reload()"></select>');_batchFilter = rsb.batchModal.batchTable.closest(".table-container").find("div.table-filter>select");_batchFilter.append("<option value='All' 'selected'>" + 'All'+ "</option>");_batchFilter.append("<option value='Unsent'>" + 'Unsent'+ "</option>");_batchFilter.append("<option value='Success'>" + 'Success'+ "</option>");_batchFilter.append("<option value='Error'>" + 'Error'+ "</option>");_batchFilter.append("<option value='Warning'>" + 'Warning'+ "</option>");_batchFilter.append("<option value='Pending'>" + 'Pending'+ "</option>");rsb.batchModal.batchTable.closest(".table-container").find("div.search-bar").html('<div class="input-group"><input type="text" class="form-control" placeholder="' + 'Search for...'+ '" onkeypress="rsb.connect.tableSearchBarKeyPress(rsb.batchModal.batchTable, event)"><button class="btn btn-outline-secondary" type="button" style="height: auto !important" onclick="rsb.batchModal.batchTable.DataTable().ajax.reload()">&nbsp;<i class="fa fa-search fa-3"></i></button></div>')},preAjax: function(opt, request) {var status = rsb.batchModal.batchTable.closest(".table-container").find("div.table-filter select").val();opt["requestData"] = {"connectorid": rsb.batchModal.updatePostData.connectorid,"workspaceid": rsb.batchModal.updatePostData.workspaceid,"direction": rsb.batchModal.updatePostData.direction,"batchgroupid": rsb.batchModal.updatePostData.batchgroupid,"islog": rsb.batchModal.updatePostData.islog,"top": request.length,"skip": request.start,"status": status};if (request.order && request.order.length > 0) {opt["requestData"]["orderbycolumn"] = request.columns[request.order[0].column].data;opt["requestData"]["orderbyorder"] = request.order[0].dir}
var searchBar = rsb.batchModal.batchTable.closest(".table-container").find("div.search-bar input");if (searchBar && searchBar.length > 0) {var searchBarText = searchBar.val().trim();if (searchBarText && searchBarText.length > 0) {opt["requestData"]["filter"] = searchBarText}}}}
rsb.initTable($("#batchInfoTable"), "src/getBatchInfo.rsb", $("#messageInfoModalResultContainer"), options);rsb.batchModal.init = true} else {rsb.batchModal.batchTable.DataTable().ajax.reload()}}
var _resetButtons = function ($isBatchMessage) {if ($isBatchMessage) {_btnDownloadLog.hide();var $downloadLogLink = _btnDownloadLog.attr("href");var $downloadMessageLink = _btnDownloadMessage.attr("href");_btnBack.show().off("click").one("click", function () {_modal.addClass("batch-info-modal");_title.text('Batch Group Info');_btnBack.hide().off("click");_btnDownloadLog.show();_resetContainer(_generalPanel);_groupPanel.show();if (!!$downloadLogLink && $downloadLogLink != "javascript:void(0);") {_btnDownloadLog.removeClass("disabled");_btnDownloadLog.attr("href", $downloadLogLink).parent().popover("dispose")}
if (!!$downloadMessageLink && $downloadMessageLink != "javascript:void(0);") {_btnDownloadMessage.removeClass("disabled");_btnDownloadMessage.attr("href", $downloadMessageLink).parent().popover("dispose")}})} else {_btnBack.hide().off("click");_btnDownloadLog.show()}
_btnDownloadLog.addClass("disabled");_btnDownloadLog.attr("href", "javascript:void(0);").parent().popover("dispose").popover({content: 'No log files found. This can occur if the log folder was manually removed.',trigger: "hover",placement: "top",container: "body"});_btnDownloadMessage.addClass("disabled");_btnDownloadMessage.attr("href", "javascript:void(0);").parent().popover("dispose").popover({content: 'No message file found. This can occur if the message was manually removed, or if SendToPort is set while LogMessages is disabled.',trigger: "hover",placement: "top",container: "body"})}
var _resetContainer = function ($container) {$container.hide();$container.children().hide();$container.find(".message-known-headers").empty();$container.find(".message-extra-headers").addClass("collapsed");$container.find(".message-extra-headers>h5").off("click");$container.find(".message-extra-headers .panel-collapse").empty();$container.find(".message-info-text").text("");$container.find(".batch-messages tbody td.filename").off("click").find("[data-bs-toggle='tooltip']").tooltip('dispose');$container.find(".batch-messages tbody").empty()}
var _reset = function () {rsb.batchModal.batchTable.closest(".table-container").find("div.search-bar input").val("");rsb.batchModal.batchTable.closest(".table-container").find(".table-filter select").val("All");_resetContainer(_groupPanel);_resetContainer(_generalPanel);_resetButtons();_generalPanel.show()}
this.show = function ($logEntity, $args) {rsb.batchModal.updatePostData.connectorid = $logEntity.connectorid;rsb.batchModal.updatePostData.workspaceid = $logEntity.workspace;rsb.batchModal.updatePostData.direction = $logEntity.direction;rsb.batchModal.updatePostData.islog = $logEntity.status == "Unsent" ? "false" : "true";rsb.batchModal.updatePostData.batchgroupid = $logEntity.messageid;_reset();_args = $args;if (!$logEntity || !$logEntity.messageid || !$logEntity.filename) {rsb.showResult(_resultContainer, 'The message id or filename MUST be set.', "error", false, false, true);_modal.modal('show');return false}
_showMessageInfo($logEntity, false)}
_modal.off('hidden.bs.modal').one('hidden.bs.modal', _reset);_reset();return this}
