rsb.providerHierarchySettings = function ($options) {var DEFAULTS = {excludedSessionProperties: true,namePrefix: ""};var _getHierarchySettingsContainer = function ($container) {$container = $($container);return $container.hasClass("provider-hierarchy-settings") ? $container : $container.find("div.provider-hierarchy-settings")}
var _options = $.extend(DEFAULTS, $options);var _requiredContainer = _getHierarchySettingsContainer(_options.requiredContainer);var _optionalContainer = _getHierarchySettingsContainer(_options.optionalContainer);var _containers = $(_requiredContainer).add($(_optionalContainer));if (!_containers || !_containers.length) {throw 'The required or optional container input is required.'}
if (!_options.driverClass) {throw 'The driver class input is required.'}
if (_containers.prop("hierarchySettings") != null) {return _containers.prop("hierarchySettings")}
var _resultContainer = rsb.getFormResultContainer(_containers.closest("form"));var _hierarchySettingsCache = {};var _connectionStringTypeChanged = function ($driverName, $driverClass, $hierarchyProperty, $args) {var postData = {...$hierarchyProperty,"@json": true,"ProviderType": _options.driverType,"ProviderName": $driverName || "other","ProviderClass": $driverClass};$.ajax({dataType: "json",url: "src/getProviderProperties.rsb",type: "POST",data: postData,success: function (data, textStatus, jqXHR) {var $props = data["items"];var $errMsg = rsb.getResultErrorMessage($props) || $props[0]["exmessage"];if ($errMsg) {rsb.showResult(_resultContainer, $errMsg, false, true)} else {_clear();var categories = [];var hierarchyProperties = [];var $showRequired = _requiredContainer && _requiredContainer.length;var $showOptional = _optionalContainer && _optionalContainer.length;var $meta = null;var $type = null;rsb.forEach($props, function ($prop, $index) {var $html = "";var $required = true;if (!$prop.name) {$meta = $prop} else if (!_options.excludedSessionProperties || !rsb.getValueAsBool($prop.issessionproperty, false)) {$required = rsb.getValueAsBool($prop.isrequired, false) || $prop.tab?.toLowerCase() === "basic";if ($required && !$showRequired || !$required && !$showOptional) {return true}
var category = $prop.category || "Optional Connection Properties";if (!$required && categories.indexOf(category.toLowerCase()) < 0) {if (!!_options.resetSchemaCache && categories.length > 0 && categories[categories.length - 1].toLowerCase() == "schema") {$html += "<div class=\"form-group row mb-3\">\n" +"  <div class=\"col-md-3\"></div>\n" +"  <div class=\"col-md-9\">\n" +"    <button type=\"button\" class=\"btn btn-outline-secondary reset-schema-btn\" data-loading-text='Reset...'><i class=\"fa fa-refresh\"></i> Reset Schema</button>\n" +"  </div>\n" +"</div>"}
categories.push(category.toLowerCase());$html += '<h4 class="page-header">' + rsb.htmlEncode(category) + '</h4>'}
$prop.value = $prop.default || "";$html += '<div class="form-group row mb-3'
if (rsb.getValueAsBool($prop.ishierarchy, false)) {$html += " hierarchy-property";$type = $prop.value}
if (hierarchyProperties.indexOf($prop.name.toLowerCase()) >= 0) {$html += " hierarchy-controller"}
if (!!$prop.extrainfo) {$html += " hierarchy-setting"}
$html += '">' +'<label for="' + $prop.name.toLowerCase() + '" class="col-md-3 control-label col-form-label">' + ($prop.displayname.toLowerCase() == 'other' ? 'Other Driver Settings' : $prop.displayname) + ':</label>';if ($prop.choice && $prop.choice.length > 1) {$prop.value = $prop.value || $prop.choice[0];$html += '<div class="col-md-6">' +'<select class="form-control form-select" name="' + _options.namePrefix + $prop.name.toLowerCase() + '" id="' + $prop.name.toLowerCase() + '"' + ($prop.description && $prop.description.length > 0 ? 'data-bs-toggle="popover" data-bs-html="true" data-bs-trigger="hover"' + (rsb.isWorkflow ? ' data-bs-placement="top"' : '') + ' data-bs-content="' + $prop.description + '"' : '') + ' data-name="' + $prop.name.toLowerCase() + '"' + ' data-hierarchy="' + ($prop.extrainfo || "").toLowerCase() + '"' + '>';rsb.forEach($prop.choice, function (choice, index) {$html += '<option value="' + choice + '"' + (choice === $prop.value ? ' selected' : '') + '>' + (choice || 'Not Specified') + '</option>'});$html += '</select>'} else {if ($prop.type == undefined) {$prop.type = "text"}
$html += '<div class="' + ($prop.type == "file" ? "col-md-6" : $prop.type == "int" ? "col-md-4 col-lg-3" : "col-md-6") + '">' +'<input type="' + (!!$prop.sensitivity ? 'password' : $prop.type == "int" ? 'number' : 'text') + '" class="form-control" name="' + _options.namePrefix + $prop.name.toLowerCase() + '" id="' + $prop.name.toLowerCase() + '" value="' + $prop.value + '"' + ($prop.description && $prop.description.length > 0 ? 'data-bs-toggle="popover" data-bs-html="true" data-bs-trigger="hover"' + (rsb.isWorkflow ? ' data-bs-placement="top"' : '') + ' data-bs-content="' + $prop.description + '"' : '') + ' data-name="' + $prop.name.toLowerCase() + '"' + ' data-hierarchy="' + ($prop.extrainfo || "").toLowerCase() + '"' + '>'}
$html += '</div></div>'}
if (!!$html && $required) {_requiredContainer.append($html)} else if (!!$html) {_optionalContainer.append($html)}});_options.driverName = $driverName;_options.driverClass = $driverClass;_requiredContainer.find('[data-bs-toggle="popover"]').popover({container: _requiredContainer});_optionalContainer.find('[data-bs-toggle="popover"]').popover({container: _optionalContainer});_containers.find("input.connection-string-type").val($type || "");!!_options.driverChanged && _options.driverChanged($meta, $type, $args);_initHierarchy()}}})}
var _controllerChanged = function ($name, $value) {$name = $name.replace(/\s/g, '').toLowerCase();$value = ($value || "").replace(/\s/g, '').toLowerCase();_containers.find(".form-group.hierarchy-setting").each(function () {var $group = $(this);var $settingEle = $group.find("input:not(.vault-setting-reference),select");if ($name == ($settingEle.data("name") || "").replace(/\s/g, '').toLowerCase()) {return true}
var $settings = _getHierarchySettings($settingEle.data("name"), $settingEle.data("hierarchy"));if (!!$settings && $settings.length) {rsb.forEach($settings, function ($setting) {if ($setting.name == $name) {var $match = false;rsb.forEach($setting.options, function ($option) {if (!$match && ($option == $value || $option == "notempty" && $value.length > 0 || $option == "empty" && $value.length == 0)) {$match = true}});var $sectionHeader = $group.prevAll("h4.page-header").first();if ($match) {var previousValue = $settingEle.prop("previousVal");if (previousValue != null && previousValue != undefined) {$settingEle.prop("previousVal", null);if ($settingEle.is("input") && ($settingEle.attr("type") == "checkbox" || $settingEle.attr("type") == "radio")) {$settingEle.prop("checked", previousValue)} else {$settingEle.val(previousValue)}
$settingEle.change()}
$settingEle.find("option").add($settingEle).removeClass("rsb-form-nosubmit");$group.removeClass("hidden");!!$sectionHeader && $sectionHeader.removeClass("hidden")} else {!!$sectionHeader && $sectionHeader.nextUntil("h4.page-header").filter(":not(.hidden)").length <= 1 && $sectionHeader.addClass("hidden");$group.addClass("hidden");$settingEle.find("option").add($settingEle).addClass("rsb-form-nosubmit");var $curval = "";if ($settingEle.is("input") && ($settingEle.attr("type") == "checkbox" || $settingEle.attr("type") == "radio")) {$curval = $settingEle.prop("checked")} else {$curval = $settingEle.val()}
$settingEle.prop("previousVal", $curval).val("").change()}}})}})}
var _getHierarchySettings = function ($name, $hierarchy) {var $settings = _hierarchySettingsCache["setting:" + $name];if (!!$settings) {return $settings}
if (!$hierarchy) {return null}
$settings = [];rsb.forEach($hierarchy.split(";"), function ($setting) {$setting = $setting.replace(/\s/g, '').toLowerCase();var $sepPos = $setting.trim().indexOf("=");if ($sepPos) {$settings.push({name: $setting.substring(0, $sepPos),options: $setting.substring($sepPos + 1).split(",")})}});_hierarchySettingsCache["setting:" + $name] = $settings;return $settings}
var _initHierarchy = function () {_containers.find(".form-group.hierarchy-property").off("change").on("change", function (event) {_connectionStringTypeChanged(_options.driverName, _options.driverClass, {"HierarchyProperty": $(event.target).data("name") || "AuthScheme", "HierarchyPropertyValue": $(event.target).val()})});_containers.find(".form-group.hierarchy-controller").each(function () {var $controller = $(this).find("input:not(.vault-setting-reference),select");if (!$controller || !$controller.length || !$controller.data("name")) {return true}
var $name = $controller.data("name").replace(/\s/g, '').toLowerCase();if (!$name) {return true}
if ($controller.is("input")) {if ($controller.attr("type") == "checkbox" || $controller.attr("type") == "radio") {$controller.off("change").on("change", function () {_controllerChanged($name, $(this).prop("checked"))})} else {$controller.off("keyup").off("change").on("keyup change", function () {_controllerChanged($name, $(this).val())})}} else if ($controller.is("select")) {$controller.off("change").on("change", function () {_controllerChanged($name, $(this).val())})}});_containers.find(".form-group.hierarchy-controller").find("input,select").change();!!_options.resetSchemaCache && _containers.find(".btn.reset-schema-btn").off("click").on("click", _options.resetSchemaCache)}
var _clear = function () {_hierarchySettingsCache = {};_containers.find("input,select").off("keyup").off("change");_containers.find('[data-bs-toggle="popover"]').popover('dispose');_containers.find(".btn").off("click");_containers.empty()}
this.refresh = function ($driverName, $driverClass, $args) {_connectionStringTypeChanged($driverName, $driverClass || _options.driverClass, null, $args)}
this.clear = function () {_clear()}
_initHierarchy();_containers.prop("hierarchySettings", this);return this}
