var rsb = rsb || {};rsb.editors = [];function $i18n(token, text) { return text; }
rsb.evalTemplate = function(template, args) {var regex = new RegExp();for (attr in args) {if (attr) {regex.compile("\\$" + attr + "\\$", "gm");template = template.replace(regex, args[attr])}}
return template}
rsb.initSettingsForms = function(form) {if (!form) {form = $(".form-settings")}
form.each(function () {var form = $(this);form.validate({errorClass: "has-error",errorPlacement: function (error, element) {var obj = $(element).closest("div.form-validate-error-container");if (obj.length <= 0 ) {obj = $(element).closest("div.form-group")}
$(error).appendTo(obj).addClass("control-label col-form-label")},highlight: function (element, errorClass, validClass) {rsb.getValidationScope(element).addClass(errorClass)},unhighlight: function(element, errorClass, validClass) {rsb.getValidationScope(element).removeClass(errorClass)},onfocusout: false,submitHandler: rsb.saveChanges})})}
rsb.checkUnsave = function(form, externalCheckUnsaveFunc) {if (form.hasClass("rsb-form-nocheckunsave")) return;var hasUnsaved = false;for (var i = 0; i < rsb.editors.length; i++) {if (rsb.editors[i].historySize().undo > 0) {hasUnsaved = true}}
var excludes = form.find(".rsb-form-nosubmit input, .rsb-form-nosubmit textarea, .rsb-form-nosubmit option, .CodeMirror textarea");var inputs = form.find("input[type=text], input[type=hidden], input[type=password], input[type=number], textarea").not(excludes);for (var i = 0; i < inputs.length; i++) {if (!$(inputs[i]).hasClass("rsb-form-nosubmit")) {if ($(inputs[i]).data("rsb.checkUnsave") != null) {if ($(inputs[i]).data("rsb.checkUnsave")()) {hasUnsaved = true}} else if ((inputs[i].type == null || inputs[i].type.toLowerCase() != "hidden") && inputs[i].defaultValue != inputs[i].value) {$(inputs[i]).parents("div.form-group").addClass("has-warning");hasUnsaved = true}}}
var inputs = form.find("input[type=radio], input[type=checkbox]").not(excludes);for (var i = 0; i < inputs.length; i++) {if (!$(inputs[i]).hasClass("rsb-form-nosubmit")) {if ($(inputs[i]).data("rsb.checkUnsave") != null) {if ($(inputs[i]).data("rsb.checkUnsave")()) {hasUnsaved = true}} else if (inputs[i].defaultChecked != inputs[i].checked) {$(inputs[i]).parents("div.form-group").addClass("has-warning");hasUnsaved = true}}}
var options = form.find("option").not(excludes);for (var i = 0; i < options.length; i++) {if (!$(options[i]).parent("select").hasClass("rsb-form-nosubmit") && !$(options[i]).hasClass("rsb-form-nosubmit")) {if ($(options[i]).parent("select").data("rsb.checkUnsave") != null) {if ($(options[i]).parent("select").data("rsb.checkUnsave")()) {hasUnsaved = true}} else if (options[i].defaultSelected != options[i].selected) {$(options[i]).parents("div.form-group").addClass("has-warning");hasUnsaved = true}}}
if (externalCheckUnsaveFunc && externalCheckUnsaveFunc()) {hasUnsaved = true}
if (hasUnsaved == true) {return 'You haven\'t saved your changes.'}}
rsb.showResultFadeOutTimeout = {};rsb.showResult = function(container, text, status, useHtml, showErrorBtn, statical, fadeDurationMs) {if (!text) return;if (!container) return;var fadeDuration = fadeDurationMs || 100;if (container.css("opacity") != '1') {container.css('opacity', '0').fadeTo(fadeDuration, 1)}
if (typeof(status) == "string") {if (status.toLowerCase() == "success") {container.fadeIn(fadeDuration).removeClass("hidden alert-danger alert-info alert-warning").addClass("alert-success fade-out")} else if (status.toLowerCase() == "error") {container.fadeIn(fadeDuration).removeClass("hidden alert-success alert-info alert-warning").addClass("alert-danger");if (container.hasClass("fade-out-except-error")) {container.removeClass("fade-out")} else {container.addClass("fade-out")}} else if (status.toLowerCase() == "info") {container.fadeIn(fadeDuration).removeClass("hidden alert-success alert-danger alert-warning").addClass("alert-info fade-out")} else if (status.toLowerCase() == "warning") {container.fadeIn(fadeDuration).removeClass("hidden alert-success alert-danger alert-info").addClass("alert-warning fade-out")} else if (status.toLowerCase() == "none" || status.toLowerCase() == "custom-error") {container.fadeIn(fadeDuration).removeClass("hidden alert-success alert-danger alert-info alert-warning").addClass("fade-out");if (container.hasClass("fade-out-except-error") && status.toLowerCase() == "custom-error") {container.removeClass("fade-out")}}} else if (typeof(status) == "boolean") {if (status) {container.fadeIn(fadeDuration).removeClass("hidden alert-danger alert-info alert-warning").addClass("alert-success fade-out")} else {container.fadeIn(fadeDuration).removeClass("hidden alert-success alert-info alert-warning").addClass("alert-danger");if (container.hasClass("fade-out-except-error")) {container.removeClass("fade-out")}}}
var containerId = container.attr("id") || "_id";if (!statical) {rsb.showResultFadeOutTimeout[containerId] = setTimeout(function() {if (container.css("opacity") == '1' && container.is(":visible")) {container.filter("div.fade-out").fadeTo(fadeDuration, 0.1).slideUp(fadeDuration)}
if (rsb.showResultFadeOutTimeout[containerId]) {clearTimeout(rsb.showResultFadeOutTimeout[containerId]);delete rsb.showResultFadeOutTimeout[containerId]}}, 10000)} else {if (rsb.showResultFadeOutTimeout[containerId]) {clearTimeout(rsb.showResultFadeOutTimeout[containerId]);delete rsb.showResultFadeOutTimeout[containerId]}}
if (useHtml != true) {text = rsb.htmlEncode(text)}
if (showErrorBtn == false) {container.find("button.btn-close").addClass("hidden")} else {container.find("button.btn-close").removeClass("hidden")}
if (container.find("content").length > 0) {container.find("content").replaceWith("<content>" + text + "</content>")} else {container.html(text)}
if (container.hasClass("ellipsis")) {container.off("dblclick").on("dblclick", function() {container.toggleClass("ellipsis")})}}
rsb.getFormData = function(form, useJson) {var data = { };var dataStrList = $(form).serializeArray();var dataIndex = { };for (var i = 0; i < dataStrList.length; i++) {var key = dataStrList[i].name;var value = dataStrList[i].value;var index = dataIndex[key] || 0;if (rsb.needSubmit($(form).find("input[name='" + key + "'],textarea[name='" + key + "'],select[name='" + key + "'],button[name='" + key + "']")[index])) {rsb.addValueToMap(data, key, value)}
dataIndex[key] = index + 1}
var checkboxList = $(form).find("input[type='checkbox']");for (var i = 0; i < checkboxList.length; i++) {var checkbox = $(checkboxList[i]);if (checkbox.attr("name")) {if (!checkbox.prop("checked") && checkbox.attr("data-uncheckvalue") != undefined && rsb.needSubmit(checkbox[0])) {rsb.addValueToMap(data, checkbox.attr("name"), checkbox.attr("data-uncheckvalue"))}}}
if (useJson && useJson == true) {data["@json"] = "true"}
return data}
rsb.setInputValue = function(input, value) {input = $(input)[0];if (input && input.type) {var triggerOnChange = false;if (input.type == "text" || input.type == "textarea" || input.type == "password" || input.type == "hidden" || input.type == "number") {triggerOnChange = (input.value != value);input.value = value} else if (input.type == "radio" || input.type == "checkbox") {var curChecked = input.checked;if (input.type == "checkbox") {input.checked = (rsb.equalsIgnoreCase(value, input.value)) ? true : false} else {input.checked = (value == input.value) ? true : false}
triggerOnChange = (input.checked != curChecked)} else if (input.tagName.toLowerCase() == "select") {var options = $(input).find("option");var selectedIndex;for (var i in options) {if (options[i].selected) selectedIndex = i}
for (var i in options) {if (rsb.equalsIgnoreCase(options[i].value, value)) {triggerOnChange = (selectedIndex != i);options[i].selected = true} else {options[i].selected = false}}}
if (triggerOnChange) {$(input).trigger("change")}}}
rsb.equalsIgnoreCase = function(lhs, rhs) {if (lhs && rhs) {return lhs.toLowerCase() == rhs.toLowerCase()} else {return lhs === rhs}}
rsb.getFormResultContainer = function(form) {var resultContainer = $(form).find("div.form-result, div.form-result-static");if (!resultContainer || resultContainer.length <= 0) {resultContainer = $("div.rsb-form-result")}
if (resultContainer && resultContainer.length > 1) {resultContainer = $(resultContainer[0])}
return resultContainer}
rsb.needSubmit = function(element) {if (element != null) {if ($(element).hasClass("rsb-form-nosubmit")) {return false} else if ($(element).hasClass("rsb-form-ifchange")) {if (element.type == "text" || element.type == "textarea" || element.type == "password" || element.type == "hidden") {return element.defaultValue != element.value} else if (element.type == "radio" || element.type == "checkbox") {return element.defaultChecked != element.checked} else if (element.tagName.toLowerCase() == "select") {var options = $(element).find("option");for (var i in options) {if (options[i].defaultSelected != options[i].selected) {return true}}
return false}}}
return true}
rsb.addValueToMap = function(map, key, value) {if (!map[key]) {map[key] = value} else if ($.isArray(map[key])) {map[key].push(value)} else {map[key] = [map[key], value]}}
rsb.htmlEncode = function(value){return $('<div></div>').text(value).html()}
rsb.stopPropagation = function(e) {e = e || window.event;if (e.stopPropagation) {e.stopPropagation()}
else {e.cancelBubble = true}}
rsb.trimStr = function(str) {return str.replace(/^\s+|\s+$/gm,'')}
rsb.xmlEscape = function(text) {return (text + '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
rsb.forEach = function(array, callback) {if (array && array.length && callback) {if (Array.prototype.forEach) {array.forEach(callback)} else {for (var index = 0; index < array.length; index++) {callback(array[index], index)}}}}
rsb.isOAuthScheme = function(authScheme) {rsb.OAuthSchemesArray = ["auto", "oauth", "azuread"];if (!authScheme || $.inArray(authScheme.toLowerCase(), rsb.OAuthSchemesArray) >= 0) {return true}
return false}
rsb.getOAuthScheme = function(authScheme, capabilities) {rsb.OAuthWebSchemesArray = ["azuread", "awsazuread", "oauth", "oauth2", "pkce", "azureadopenid", "genericoauth", "oauthpkce"];rsb.OAuthAppSchemesArray = ["azuremsi", "oauthjwt", "gcpinstanceaccount", "azureserviceprincipal", "sharepointoauth", "oauthclient", "oauthimplicit", "oauthpassword", "oauthsaml1", "oauthsaml2", "azurepassword", "companylevelauth", "gcpserviceaccount", "genericoauthclient"];var defaultCapability = "";if (capabilities && capabilities.indexOf("OAUTH_WEB") >= 0) {defaultCapability = "OAUTH,OAUTH_WEB"} else if(capabilities && capabilities.indexOf("OAUTH_APP") >= 0) {defaultCapability = "OAUTH,OAUTH_APP"}
if(!authScheme || authScheme.toLowerCase() === "auto") {return defaultCapability} else if ($.inArray(authScheme.toLowerCase(), rsb.OAuthWebSchemesArray) >= 0) {return "OAUTH,OAUTH_WEB"} else if ($.inArray(authScheme.toLowerCase(), rsb.OAuthAppSchemesArray) >= 0) {return "OAUTH,OAUTH_APP"} else  {return ""}}
rsb.resetConnection = function(queryData, btn, resultContainer, capabilities, queryDataCallback, oauthSuccessCallback, oauthErrorCallback, beforeOAuth, testConnectionErrorCallback) {if (beforeOAuth) {beforeOAuth()}
rsb.oauth(queryData, btn, resultContainer, capabilities, queryDataCallback, function(queryData){rsb.testConnection(queryData, btn, resultContainer, oauthSuccessCallback, testConnectionErrorCallback || oauthErrorCallback)}, oauthErrorCallback)}
rsb.oauth = function(queryData, btn, resultContainer, capabilities, queryDataCallback, successCallback, oauthErrorCallback, downloadBtn) {downloadBtn = downloadBtn ? downloadBtn : "";btn.button("loading");queryData["@json"] = true;capabilities = (capabilities || "").toUpperCase();var oauthFlow = rsb.getOAuthScheme(queryData.authscheme, capabilities) || "";if (oauthFlow.indexOf("OAUTH_APP") >= 0) {$.ajax({dataType: "json",url: "src/getOAuthAccessToken.rsb",type: "POST",data: queryData,success : function(data) {var result = data["items"];var errorMsg = rsb.getResultErrorMessage(result);if (errorMsg) {errorMsg = "<div class='row'><div class='col-md-9'>" + errorMsg + "</div><div class='col-md-auto ms-auto'>" + downloadBtn + "</div>";rsb.showResult(resultContainer, 'OAuth connection failed'+ ': ' + errorMsg, false, true);!!oauthErrorCallback && oauthErrorCallback(queryData, errorMsg)} else {if (queryDataCallback) {queryData = queryDataCallback(result[0])}
successCallback(queryData)}}}).always(function() {btn.button("reset")})} else if (oauthFlow.indexOf("OAUTH_WEB") >= 0) {$.ajax({dataType: "json",url: "src/getOAuthAuthorizationURL.rsb",type: "POST",data: queryData,success : function(data) {var result = data["items"];var errMsg = rsb.getResultErrorMessage(result);if(errMsg) {errMsg = "<div class='row'><div class='col-md-9'>" + errMsg + "</div><div class='col-md-auto ms-auto'>" + downloadBtn + "</div>";rsb.showResult(resultContainer, '<b>Failure!</b>&nbsp;&nbsp;'+ errMsg, false, true);btn.button("reset");!!oauthErrorCallback && oauthErrorCallback(queryData, errMsg)} else {var url = result[0]["url"];delete result[0]["url"];var reqUrl = "src/setOAuthParamsInSession.rst";$.post(reqUrl, $.extend(queryData, result[0]));var isOAuthDone = false;var oauthCallbackTimer = null;window.onOAuthCallbackDone = function(doc) {if (isOAuthDone) return;isOAuthDone = true;oauthCallbackTimer && clearInterval(oauthCallbackTimer);btn.button("reset");doc = $(doc);var input = doc.find('#errormessage');if (input && input.length > 0) {var errorMsg = "<div class='row'><div class='col-md-9'>" + input.val() + "</div><div class='col-md-auto ms-auto'>" + downloadBtn + "</div>";rsb.showResult(resultContainer, '<b>Failure!</b>&nbsp;&nbsp;'+ errorMsg, false, true);!!oauthErrorCallback && oauthErrorCallback(queryData, errorMsg)} else {if (queryDataCallback) {var data = {};doc.find('input').each(function () {data[$(this).attr("id")] = $(this).val()});queryData = queryDataCallback(data)}
successCallback(queryData)}}
if (!result[0] || !url) {rsb.showResult(resultContainer, '<b>Failure!</b>&nbsp;&nbsp;Get the OAuth authorization URL failed.'+ downloadBtn,  false, true);btn.button("reset");return}
var win = window.open(url, '_blank');win && win.focus();var loopCount = 0;oauthCallbackTimer = setInterval(function() {if (isOAuthDone) return;if (!win || win.closed) {$.ajax({dataType: "json",url: "src/getOAuthCallbackFromSession.rsb?@json",type: "GET",async: false,success: function(data, textStatus, jqXHR) {if (isOAuthDone) return;var oauth_callback = data.items && data.items.length && data.items[0].oauth_callback;var oauth_callback_error = data.items && data.items.length && data.items[0].oauth_callback_error;if (oauth_callback) {isOAuthDone = true;clearInterval(oauthCallbackTimer);btn.button("reset");if (queryDataCallback) {queryData = queryDataCallback(JSON.parse(oauth_callback))}
successCallback(queryData,JSON.parse(oauth_callback))} else if (oauth_callback_error || win) {clearInterval(oauthCallbackTimer);btn.button("reset");rsb.showResult(resultContainer, $i18n("static_js_0003", downloadBtn + "<b>Failure!</b>&nbsp;&nbsp;") + (oauth_callback_error || 'An error occurred while attempting to obtain authorization.'), false, true);!!oauthErrorCallback && oauthErrorCallback(queryData, downloadBtn + (oauth_callback_error || 'An error occurred while attempting to obtain authorization.'))} else if (++loopCount >= 300) {clearInterval(oauthCallbackTimer);btn.button("reset");rsb.showResult(resultContainer, '<b>Failure!</b>&nbsp;&nbsp;'+ downloadBtn, false, true);!!oauthErrorCallback && oauthErrorCallback(queryData, downloadBtn)}}})}}, 200)}}})} else {successCallback(queryData)}}
rsb.testConnection = function(queryData, btn, resultContainer, successCallback, errorCallback, oauth_callback) {btn.button("loading");queryData["@json"] = true;$.ajax({dataType: "json",url: "src/testConnection.rsb?@json",type: "POST",data: queryData,success: function(data, textStatus, jqXHR) {var result = data["items"];var errMsg = rsb.getResultErrorMessage(result);if(errMsg) {rsb.showResult(resultContainer, "<b>Failure!</b>&nbsp;&nbsp;" + errMsg, false, true);if (errorCallback) errorCallback(queryData, errMsg)} else {rsb.showResult(resultContainer, btn.attr("data-success-message") ? btn.attr("data-success-message"): "<b>Success!</b>", true, true);if (successCallback) successCallback(queryData, result, oauth_callback)}}}).always(function() {btn.button("reset")})}
rsb.getResultErrorMessage = function(result) {return rsb.getResultErrorMessageByIndex(result, 0)}
rsb.getResultErrorMessageByIndex = function(result, i) {var errorMsg = null;if (result && result.length > i) {errorMsg = result[i]["rsb:emessage"] || result[i]["errormessage"];if (errorMsg == "") {errorMsg = 'Unknown error'}}
return errorMsg}
rsb.escapeSelector = function(str) {if (str) {return $.escapeSelector(str)}
return str}
rsb.loadedModalList = rsb.loadedModalList || [];rsb._loadingModalList = rsb._loadingModalList || [];rsb._loadingModalTimeout = rsb._loadingModalTimeout || null;rsb._loadingModalImpl = function() {if (rsb._loadingModalList.length <= 0) {rsb._loadingModalTimeout = null;return}
if ($.active) {rsb._loadingModalTimeout = setTimeout(rsb._loadingModalImpl, 100);return}
var modalInfo = rsb._loadingModalList.shift();if (rsb.loadedModalList.indexOf(modalInfo.name + "|" + JSON.stringify(modalInfo.data)) < 0) {$.ajax({dataType: "html",url: "src/loadModal.rst",data: $.extend({"modal": modalInfo.name}, modalInfo.data),type: "GET",success: function(data, textStatus, jqXHR) {var modal = $(data);$(".modal-container").append(modal);rsb.initSettingsForms(modal.find(".form-settings"));rsb.initModal(modal.hasClass("modal") ? modal : modal.find(".modal"));rsb.loadedModalList = rsb.loadedModalList.concat(modalInfo.name + "|" + JSON.stringify(modalInfo.data));if (modalInfo.callback) {modalInfo.callback()}
rsb._loadingModalImpl()}})} else {if (modalInfo.callback) {modalInfo.callback()}
rsb._loadingModalImpl()}}
rsb.loadModal = function(name, arg1, arg2) {var data = {};var callback = null;if (arg2) {data = arg1;callback = arg2} else if (typeof(arg1) == "object") {data = arg1}  else if (typeof(arg1) == "function") {callback = arg1}
if (rsb.loadedModalList.indexOf(name) < 0 && rsb.loadedModalList.indexOf(name + "|" + JSON.stringify(data)) < 0) {rsb._loadingModalList.push({name: name,data: data,callback: callback});if (rsb._loadingModalTimeout == null) {rsb._loadingModalTimeout = setTimeout(rsb._loadingModalImpl, 100)}} else {if (callback) {callback()}}}
rsb.openingModal = null;rsb.pendingModals = [];rsb.initModal = function($modal) {$modal.on("show.bs.modal", function (e) {window.parent?.reactObj?.callbacks?.setModalOpen?.(true);if (rsb.openingModal == null && !$(this).hasClass("terms-modal")) {$(".modal:visible").addClass("hidden")} else if (rsb.openingModal) {rsb.pendingModals.push(this);e.preventDefault()} else {rsb.openingModal = this}}).on("hidden.bs.modal", function () {window.parent?.reactObj?.callbacks?.setModalOpen?.(false);rsb.openingModal = null;if (rsb.pendingModals.length > 0) {$(rsb.pendingModals.shift()).modal("show")} else if (!$(this).hasClass("terms-modal")) {$(".modal.hidden").removeClass("hidden")}}).on('shown.bs.modal', function () {rsb.getFirstFormElement(this).focus()})}
rsb.isSync = function() {var prod = $("body").attr("data-prod");if (prod && prod.toLowerCase() == "cdata sync") {return true}
return false}
rsb.securityRand = function() {if(Int32Array && window.crypto && window.crypto.getRandomValues) {var rands = new Uint32Array(1);window.crypto.getRandomValues(rands);return rands[0]} else {return Math.random()}}
rsb.getValueAsBool = function(val, defaultValue) {if (defaultValue === undefined || defaultValue == null) defaultValue = false;else defaultValue = rsb.getValueAsBool(defaultValue);if (val === undefined || val == null) return defaultValue;if (typeof val === "boolean") return val;return /^\s*(true|1|on|yes|y)\s*$/i.test(val)}
rsb.keepalive = function () {var enable = false;var running = false;var interval = 60 * 1000;var lastHeartbeatTime = Date.now();var heartbeat = function() {if ((Date.now() - lastHeartbeatTime) > interval && !running && enable) {running = true;$.post({url: "src/sessionHeartbeat.rsb",complete: function() {lastHeartbeatTime = Date.now();running = false;enable = false}})}}
window.setInterval(heartbeat, 10 * 1000);$(document).on("mousemove", function() {enable = true;heartbeat()});$(document).on("keydown", function() {enable = true;heartbeat()})};$(document).ready(function() {rsb.initModal($(".modal"))});